'use client';
import {useState,useEffect,useCallback} from 'react';
import {Download,RefreshCw,Loader2} from 'lucide-react';
import {SETORES_RELATORIO} from '@/lib/relatorio-producao-resumo';
import {NOMES_SETORES,planilhaStatusProducao} from '@/lib/relatorio-producao-excel';
import {downloadWorkbook} from '@/lib/excel-relatorio';
const pct=v=>v==null?'—':`${v.toLocaleString('pt-BR',{maximumFractionDigits:1})}%`;
export default function ResumoProducao(){
 const [dados,setDados]=useState(null),[erro,setErro]=useState(''),[loading,setLoading]=useState(true),[exportando,setExportando]=useState(false);
 const carregar=useCallback(async()=>{setLoading(true);setErro('');try{const r=await fetch('/api/pcp/relatorio-producao',{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error);setDados(j);}catch(e){setErro(e.message);}finally{setLoading(false)}},[]);
 useEffect(()=>{carregar()},[carregar]);
 async function exportar(){setExportando(true);setErro('');try{const wb=await planilhaStatusProducao(dados);await downloadWorkbook(wb,`Torg_Status_Producao_${new Date().toISOString().slice(0,10)}.xlsx`)}catch(e){setErro(e.message)}finally{setExportando(false)}}
 return <section className="space-y-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold text-torg-dark">Execução das OPs por setor</h2><p className="text-xs text-torg-gray mt-1">LPC × produção apontada no próprio setor. Avanço acumulado do Corte à Pintura.</p><p className="text-xs text-torg-gray mt-1">Última sincronização: {dados?.sincronizadoEm?new Date(dados.sincronizadoEm).toLocaleString('pt-BR'):'não informada'}</p></div><div className="flex gap-2"><button onClick={carregar} disabled={loading} className="border rounded-lg px-3 py-2 text-sm inline-flex gap-2 items-center"><RefreshCw size={14}/>Atualizar</button><button onClick={exportar} disabled={loading||exportando||!dados?.ops?.length} className="bg-torg-blue text-white rounded-lg px-3 py-2 text-sm inline-flex gap-2 items-center disabled:opacity-40">{exportando?<Loader2 size={14} className="animate-spin"/>:<Download size={14}/>}Status geral (Excel)</button></div></div>
 {erro&&<p role="alert" className="text-red-700 bg-red-50 rounded p-3">{erro}</p>}
 {loading?<p className="py-10 text-center text-torg-gray">Carregando apontamentos e escopo da LPC…</p>:!erro&&<div className="overflow-x-auto bg-white border rounded-xl"><table className="w-full text-xs min-w-[950px]"><thead className="bg-gray-50"><tr>{['OP / Cliente','Execução geral',...SETORES_RELATORIO.map(s=>NOMES_SETORES[s])].map(h=><th key={h} className="text-left p-3">{h}</th>)}</tr></thead><tbody>{dados?.ops?.map(o=><tr key={o.opId} className="border-t"><td className="p-3"><b className="text-torg-dark">OP-{o.numero}</b><span className="block text-gray-500 mt-1">{o.cliente}</span><span className="block text-gray-500">{o.obra}</span></td><td className="p-3 font-semibold" title={o.base}>{pct(o.pctGeral)}<span className="block text-[10px] font-normal text-gray-500 mt-1">{o.base}</span></td>{SETORES_RELATORIO.map(k=>{const s=o.setores[k];return <td className="p-3" key={k} title={`${s.feitoUn} de ${s.totalUn} unidades · ${s.situacao}`}><b className={s.pct===100?'text-emerald-700':'text-torg-dark'}>{pct(s.pct)}</b><span className="block text-[10px] text-gray-500 mt-1">{s.situacao}</span><span className="block text-[10px] text-gray-500">{s.totalUn?`${s.feitoUn} / ${s.totalUn} un`:''}</span></td>})}</tr>)}</tbody></table>{!dados?.ops?.length&&<p className="p-8 text-center text-gray-500">Nenhuma OP em aberto com LPC de fabricação.</p>}</div>}
 <p className="text-[11px] text-torg-gray">Geral ponderado pelo peso previsto em cada etapa; sem pesos completos, usa unidades por etapa. Não equivale ao percentual financeiro ou expedido. OPs encerradas, canceladas e com todas as etapas concluídas saem automaticamente.</p></section>
}
