"use client";
import { useState } from 'react';
import { Plus, Droplets, Layers, FileText, ChevronRight, Trash2, Paintbrush } from 'lucide-react';
import { CAMADAS_TINTA, FATURAMENTO, FATURAMENTO_ROTULO, ESTRUTURA_ROTULO } from '@/lib/lqc';
import s from './Pintura.module.css';
import { calcularCamadasPintura, estruturasDoQuantitativo, chaveAreaPintura, pinturaComDestino, atualizarDemao, custoHistoricoDaDemao, usarConsumoDaDemao } from '@/lib/lqc';
import { DocumentosPintura } from './DocumentosPintura';
import { CotacaoTinta } from './CotacaoTinta';
const numero = v => Number(v || 0).toLocaleString('pt-BR', {maximumFractionDigits:2});
const dinheiro = v => Number(v || 0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function Pintura({ c, res, setComp, estudoId }) {
 const tintas = Array.isArray(c.tintas) ? c.tintas : [];
 const setC = (fn) => setComp(fn({ ...c, tintas }));
 const [ativo,setAtivo]=useState(0),[vista,setVista]=useState('Sistema de pintura');
 const camadas = calcularCamadasPintura(c);
 const linhasAtivas = (c.resumos || []).filter(l => l.ativo !== false);
 const indice = Math.min(ativo, Math.max(0, tintas.length - 1));
 const estruturas=estruturasDoQuantitativo(c);
 const t=tintas[indice] || {};
 const calc=camadas[indice] || {};
 const material=res.grupos.tintas.total.subtotal;
 const custoHistorico=custoHistoricoDaDemao(tintas,indice);
 const alterar=(campo,valor)=>setComp({tintas:atualizarDemao(tintas,indice,{[campo]:valor})});
 const campo=(rotulo,chave,unidade,extra={})=><label className={s.campo}>{rotulo}<div className={s.entrada}><input aria-label={rotulo} type="number" min="0" step="any" value={t[chave]??''} onChange={e=>alterar(chave,e.target.value)} {...extra}/>{unidade&&<span>{unidade}</span>}</div></label>;
 const adicionar=()=>{const id=crypto.randomUUID();setC(a=>({...a,tintas:[...a.tintas,{id,camada:'INTERMEDIÁRIO',produto:'',cor:'',solidos:'',peliculaSeca:'',precoLitro:'',perda:45,estruturaEscopo:'todas'}]}));setAtivo(tintas.length);};
 return <section className={s.raiz}>
  <div className={s.resumo}><div><span>Área do escopo</span><strong>{numero(res.areaM2)} <small>m²</small></strong><small>{linhasAtivas.length} áreas · {numero(res.pesoTotal/1000)} Ton</small></div><div><span>Consumo de produtos</span><strong>{numero(camadas.reduce((v,x)=>v+(x.litros||0),0))} <small>L de tinta</small></strong><small>{numero(camadas.reduce((v,x)=>v+(x.litrosDiluente||0),0))} L de diluente</small></div><div className={s.total}><span>Custo dos produtos</span><strong data-testid="custo-tintas">{dinheiro(material)}</strong><small>Tintas + diluente · antes do BDI</small></div></div>
  <div className={s.navegacao}><nav aria-label="Visualização da pintura">{['Sistema de pintura','Áreas e custos','Documentos e cotação'].map(v=><button key={v} aria-pressed={vista===v} onClick={()=>setVista(v)}>{v}</button>)}</nav><label>Compra da tinta<select aria-label="Compra da tinta" value={c.faturamento?.tintas || ''} onChange={e=>setC(a=>({...a,faturamento:{...a.faturamento,tintas:e.target.value}}))}><option value="">Selecione</option>{FATURAMENTO.map(v=><option key={v} value={v}>{FATURAMENTO_ROTULO[v]}</option>)}</select></label></div>
  {vista==='Sistema de pintura'&&<div className={s.sistema}>
   <aside className={s.camadas}><div className={s.legenda}><Layers size={16}/> DEMÃOS <span>{tintas.length}</span></div><p>Selecione uma demão para compor.</p>{tintas.map((x,i)=>{const a=camadas[i]||{};return <button className={s.camada} key={x.id || i} aria-pressed={i===indice} onClick={()=>setAtivo(i)}><span className={s.ordem}>{String(i+1).padStart(2,'0')}</span><div><strong>{x.camada==='PRIMER'?'Primer':x.camada==='ACABAMENTO'?'Acabamento':'Intermediário'}</strong><small>{x.cor||'Cor a definir'} · {x.peliculaSeca||'—'} µm · perda {x.perda??45}%</small><b>{dinheiro(a.total)}</b></div><ChevronRight size={15}/></button>})}<button className={s.adicionar} onClick={adicionar}><Plus size={16}/> Adicionar demão</button><div className={s.nota}>As cores do acabamento são vinculadas às áreas do quantitativo.</div></aside>
   {tintas.length > 0 ? <div className={s.ficha}><header><div><span className={s.sobre}>COMPOSIÇÃO DA DEMÃO</span><h3>{t.camada==='PRIMER'?'Primer':t.camada==='ACABAMENTO'?'Acabamento':'Intermediário'}</h3></div><span className={s.area}>{numero(calc.areaM2)} m² de aplicação</span></header>
    <div className={s.formulario}><div className={s.identificacao}><label className={s.campo}>Etapa<select aria-label="Etapa" value={t.camada || ''} onChange={e=>alterar('camada',e.target.value)}>{CAMADAS_TINTA.map(x=><option key={x}>{x}</option>)}</select></label><label className={s.campo}>Produto<input aria-label="Produto" placeholder="Nome da tinta ou referência" value={t.produto || ''} onChange={e=>alterar('produto',e.target.value)}/></label><label className={s.campo}>Cor<input aria-label="Cor" value={t.cor || ''} placeholder="Ex.: Azul" onChange={e=>alterar('cor',e.target.value)}/></label></div>
     <div className={s.subtitulo}><Paintbrush size={16}/><h4>Especificação e preço</h4></div><div className={s.tecnica}>{campo('Sólidos por volume','solidos','%',{max:100})}{campo('Película seca','peliculaSeca','µm')}{campo('Preço por litro','precoLitro','R$/L')}{campo('Perda desta demão','perda','%',{max:100})}<label className={s.campo}>Aplicar nas estruturas<select aria-label="Aplicar nas estruturas" value={t.estruturaEscopo||`legado:${t.perda??45}`} onChange={e=>{const estruturaEscopo=e.target.value;setComp({tintas:atualizarDemao(tintas,indice,{estruturaEscopo,areaM2:''})});}}><option value="todas">Todas as estruturas do Quantitativo</option>{(!pinturaComDestino(t)||String(t.estruturaEscopo).startsWith("legado:"))&&<option value={t.estruturaEscopo||`legado:${t.perda??45}`}>Estruturas do sistema importado ({String(t.estruturaEscopo||`legado:${t.perda??45}`).split(":")[1]}%)</option>}{estruturas.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}{t.estruturaEscopo&&t.estruturaEscopo!=='todas'&&!String(t.estruturaEscopo).startsWith('legado:')&&!estruturas.some(x=>x.id===t.estruturaEscopo)&&<option value={t.estruturaEscopo}>Estrutura fora do Quantitativo — selecione outra</option>}</select><small className={s.origemEstrutura}>{(t.estruturaEscopo&&t.estruturaEscopo!=='todas'?estruturas.filter(x=>x.id===t.estruturaEscopo):estruturas).map(x=>`${x.nome}: ${x.areas.join(', ')}`).join(' · ')||'Informe as estruturas no Quantitativo.'}</small></label><label className={s.campo}>Aplicar na área<select aria-label="Aplicar na área" value={t.areaEscopo||'todas'} onChange={e=>{
       const escolhida=e.target.value;
       const resumos=(c.resumos||[]).map(l=>({...l,id:l.id||crypto.randomUUID()}));
       const original=(c.resumos||[]).findIndex((l,i)=>chaveAreaPintura(l,i)===escolhida);
       const areaEscopo=escolhida==='todas'?'todas':original>=0?resumos[original].id:escolhida;
       setComp({resumos,tintas:atualizarDemao(tintas,indice,{areaEscopo,areaM2:''})});
     }}><option value="todas">Todas as áreas do destino</option>{(c.resumos||[]).map((l,i)=>l.ativo!==false&&<option key={chaveAreaPintura(l,i)} value={chaveAreaPintura(l,i)}>{l.item||i+1} · {l.area||'Área não informada'}</option>)}{t.areaEscopo&&t.areaEscopo!=='todas'&&!(c.resumos||[]).some((l,i)=>l.ativo!==false&&chaveAreaPintura(l,i)===t.areaEscopo)&&<option value={t.areaEscopo}>Área fora do Quantitativo — selecione outra</option>}</select></label></div>
     <div className={s.perda}>Perda individual desta demão: <b>{t.perda??45}%</b><span>A mudança não altera a perda das demais demãos.</span></div>
     <details className={s.opcionais}><summary>Ajustes da demão e diluente</summary><p>Área em branco segue o quantitativo. O consumo acompanha o destino e a cor selecionados.</p><div className={s.tecnica}>{campo('Área manual da demão','areaM2','m²',{placeholder:'Automática'})}{campo('Preço do diluente','precoDiluente','R$/L')}{campo('Proporção de diluente','diluentePct','%',{placeholder:'25'})}</div></details>
     {!(Number(t.solidos)>0&&Number(t.peliculaSeca)>0&&Number(t.precoLitro)>0)&&<p className={s.aviso}>Informe sólidos, película e preço para calcular o custo desta demão.</p>}
     {!(calc.areaM2>0)&&<p className={s.aviso}>Nenhuma área atende à estrutura selecionada{t.camada==='ACABAMENTO'?' e à cor desta demão':''}. Confira o Quantitativo e o destino da demão.</p>}
     {custoHistorico>0&&<div className={s.aviso}><p>Este grupo usa o custo histórico fechado de {dinheiro(custoHistorico)}/kg. Alterar o preço por litro atualiza a estimativa da demão; o total do grupo continua pelo valor histórico.</p><button type="button" className={s.trocarCalculo} onClick={()=>setComp({tintas:usarConsumoDaDemao(tintas,indice)})}>Calcular produtos pelo consumo</button><small>A troca vale para todas as demãos deste grupo e preserva seus produtos, perdas e destinos.</small></div>}
    </div>
    <div className={s.estimativa}><div className={s.subtitulo}><Droplets size={16}/><h4>Consumo previsto</h4><small>Atualiza durante o preenchimento</small></div><div className={s.resultados}><div><span>Rendimento prático</span><strong>{numero(calc.pratico)} <small>m²/L</small></strong><small>Teórico: {numero(calc.teorico)} m²/L</small></div><div><span>Tinta necessária</span><strong data-testid="litros-camada">{numero(calc.litros)} <small>L</small></strong><small>Diluente: {numero(calc.litrosDiluente)} L</small></div><div className={s.custo}><span>Custo da demão</span><strong data-testid="custo-camada">{dinheiro(calc.total)}</strong><small>Tinta + diluente</small></div></div></div>
    <footer><span>Especificações e quantidades vinculadas a este estudo.</span>{<button onClick={()=>{setC(a=>({...a,tintas:a.tintas.filter((_,i)=>i!==indice)}));setAtivo(Math.max(0,indice-1));}}><Trash2 size={14}/> Remover demão</button>}</footer>
   </div> : <div className={s.painel}><h3>Componha o sistema de pintura</h3><p>Adicione a primeira demão para definir produto, destino e consumo.</p><button type="button" className={s.adicionar} onClick={adicionar}><Plus size={16}/> Adicionar primeira demão</button></div>}
  </div>}
  {vista==='Áreas e custos'&&<div className={s.painel}><h3>Distribuição por área da obra</h3><p>Conferência do esquema, cor e consumo das áreas ativas do Quantitativo.</p><div className={s.tabela}><table><thead><tr>{['Área / estrutura','Cor final','Superfície','Película total','Tinta','Diluente','Custo de materiais'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{res.pinturaPorArea.map((x,i)=><tr key={i}><td><strong>{x.area || "Área não informada"}</strong><small>Item {linhasAtivas[i]?.item || x.item || '—'} · {linhasAtivas[i]?.estruturaNome || ESTRUTURA_ROTULO[linhasAtivas[i]?.estrutura] || linhasAtivas[i]?.estrutura || 'Estrutura não informada'}</small><small>{x.camadas.map(a=>a.camada).join(' + ')}</small></td><td><span className={s.azul}/> {x.cor || 'Cor não informada'}</td><td>{numero(x.areaM2)} m²</td><td>{numero(x.peliculaTotal)} µm</td><td>{numero(x.litros)} L</td><td>{numero(x.litrosDiluente)} L</td><td><b>{dinheiro(x.custo)}</b></td></tr>)}</tbody></table></div>{tintas.some(x=>Number(x.areaM2)>0||Number(x.precoKg)>0)&&<p className={s.aviso}>Há ajustes manuais de área ou custo. A área manual é distribuída entre os destinos selecionados. Um custo fechado por kg substitui o total calculado do grupo.</p>}</div>}
  {vista==='Documentos e cotação'&&<div className={s.documentos}><div className={s.painel}><FileText size={25}/><h3>Sistema de pintura e fichas técnicas</h3><p>Especificação da obra e documentos usados na composição.</p><DocumentosPintura c={c} setComp={setComp}/></div><div className={s.painel}><CotacaoTinta estudoId={estudoId} c={c} res={res}/></div></div>}
 </section>;
}
