import { CSS } from '@/app/pcp/producao/_gantt/css';
export async function GET() {
const barra = (op, p, color, tone, extra='') => `<div class="barra-op ${extra}" style="--c:${color};--ct:${tone};width:100%;position:relative;cursor:default"><div class="prog" style="width:${p}%"></div><b>OP-${op}</b><span>46 pç · 1,8 Ton</span><span class="selo">${p}% · ${Math.round(46*(1-p/100))} a fazer</span></div>`;
return new Response(`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>PCP · Prévia do preenchimento</title><style>${CSS}
*{box-sizing:border-box}body{margin:0;background:#f4f6f9;color:#0d2840;font:14px -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}main{max-width:1120px;padding:36px 24px;margin:auto}header{border-bottom:3px solid #f4801f;padding-bottom:24px;margin-bottom:28px}h1{font-size:28px;margin:8px 0 12px;letter-spacing:-.7px}p{color:#617788;line-height:1.6}.eyebrow{font-size:11px;letter-spacing:1.3px;text-transform:uppercase}section{background:white;border:1px solid #e1e8ee;border-radius:10px;padding:26px;margin:22px 0}h2{font-size:17px;margin:0 0 20px}.compare{display:grid;grid-template-columns:1fr 1fr;gap:32px}.caption{font-size:12px;color:#617788;margin-bottom:14px}.new .barra-op{color:#122b40;background:#f6f8fa}.new .barra-op .prog{top:0;bottom:0;height:100%;opacity:.26;border-radius:0;z-index:1}.new .barra-op b{color:#122b40;text-shadow:none;flex-shrink:0}.new .barra-op span{opacity:1;color:#263f52}.new .barra-op .selo{background:rgba(255,255,255,.87);color:#18354b;flex-shrink:0;border-color:transparent}.new .barra-op .selo.atr{background:#c62828;color:white}.row{display:grid;grid-template-columns:145px 1fr;align-items:center;gap:22px;border-bottom:1px solid #edf1f5;min-height:64px}.row:last-child{border:0}.row label{font-size:12px;color:#617788}.grid{background:repeating-linear-gradient(90deg,#fff 0,#fff calc(20% - 1px),#eef2f5 calc(20% - 1px),#eef2f5 20%);padding:8px 0}.controls{display:flex;align-items:center;gap:16px;margin-top:25px;font-size:12px;color:#617788}input{accent-color:#007b78;flex:1;max-width:350px}.note{font-size:12px;margin-bottom:0}footer{font-size:12px;color:#617788;padding-top:10px}@media(max-width:750px){.compare{grid-template-columns:1fr}.row{grid-template-columns:1fr;gap:10px;padding:14px 0}section{padding:18px}main{padding:24px 15px}.new .barra-op .selo{max-width:45%}h1{font-size:23px}}
</style><main><header><div class="eyebrow">Torg · PCP · Prévia local</div><h1>O avanço passa a preencher a própria barra</h1><p>A cor ocupa toda a altura e avança da esquerda para a direita. O fundo suave mantém as informações legíveis, inclusive quando o preenchimento passa por baixo do texto.</p></header>
<section><h2>A mesma OP, com 11% de avanço</h2><div class="compare"><div><div class="caption">Atual · faixa fina no rodapé</div><div class="gpcp">${barra('097',11,'#087f78','#e3efed')}</div></div><div><div class="caption">Proposta · preenchimento em toda a altura</div><div class="gpcp new">${barra('097',11,'#087f78','#e3efed')}</div></div></div></section>
<section><h2>Como fica durante a produção</h2><div class="gpcp new"><div class="row"><label>Ainda não iniciou</label><div class="grid">${barra('112',0,'#006eab','#e7f1f8')}</div></div><div class="row"><label>Em andamento</label><div class="grid">${barra('097',35,'#087f78','#e3efed')}</div></div><div class="row"><label>Próxima de concluir</label><div class="grid">${barra('106',78,'#716631','#f2efde')}</div></div><div class="row"><label>Etapa concluída</label><div class="grid">${barra('089',100,'#457946','#e8f0e8')}</div></div></div><p class="note">A largura representa o percentual apontado. A cor continua identificando a OP; o texto permanece escuro em toda a barra.</p></section>
<section><h2>Teste a leitura em qualquer percentual</h2><div class="gpcp new" id="demo">${barra('097',11,'#087f78','#e3efed')}</div><div class="controls"><label for="advance">Avanço</label><input id="advance" type="range" min="0" max="100" value="11"><output id="value">11%</output></div></section><footer>Exemplos demonstrativos · Somente visual · Nenhuma alteração publicada</footer></main><script>document.getElementById('advance').addEventListener('input',e=>{const p=Number(e.target.value);document.querySelector('#demo .prog').style.width=p+'%';document.querySelector('#demo .selo').textContent=p+'% · '+Math.round(46*(1-p/100))+' a fazer';document.getElementById('value').textContent=p+'%';});</script></html>`, {headers:{'Content-Type':'text/html; charset=utf-8'}});
}
