import {describe,it,expect} from 'vitest';
import {limitesRotacionados,ajustarVolume,recalcularMontagem,aplicarEdicaoMontagem} from '@/lib/carga/montagem-manual';
const item=(id,x=0,y=0)=>({id,volume:id==='a'?1:2,C:2000,L:300,A:600,x,y,z:0,kg:100,tipo:'PECA',membros:[{id:`p-${id}`,marca:id,kg:100,C:2000,L:300,A:600}]});
const carga=()=>({veiculo:{C:8500,L:2450,alturaUtil:2600,pesoMax:12000},itens:[item('a'),item('b',3000)],passos:['a','b'],peso:200,romaneio:[],madeira:{pecas:{}}});
describe('edição manual da montagem',()=>{
 it('gira em 90° sem alterar a geometria original nem a quantidade',()=>{const a=item('a');const editada=ajustarVolume(a,{x:100,y:50,z:200,rotacao:{x:90,y:0,z:0}});expect(editada.C).toBe(2000);expect(editada.A).toBe(600);expect(editada.fx).toBeCloseTo(2000);expect(editada.fy).toBeCloseTo(300);expect(editada.fz).toBeCloseTo(600);expect(editada.membros).toEqual(a.membros);expect(a.x).toBe(0);});
 it('considera a orientação atravessada antes do giro manual',()=>{expect(limitesRotacionados({...item('a'),girada:true},{x:0,y:90,z:0}).tamanho).toEqual(expect.objectContaining({x:2000,y:600,z:300}));});
 it('recalcula altura, apoios e alerta quando a ordem põe o volume superior primeiro',()=>{const c=carga();c.itens[1]={...item('b',0,700)};c.passos=['b','a'];const r=recalcularMontagem(c);expect(r.altura).toBe(1300);expect(r.itens[1].sobre).toEqual(['a']);expect(r.verificacoes.some(v=>v.tipo==='ordem')).toBe(true);});
 it('avisa sobre colisão e limites da carroceria',()=>{const c=carga();c.itens[1]=item('b',100);expect(recalcularMontagem(c).verificacoes.some(v=>v.tipo==='colisao')).toBe(true);c.itens[1]=item('b',8000);expect(recalcularMontagem(c).verificacoes.some(v=>v.tipo==='limite')).toBe(true);});
 it('salva posições e sequência preservando veículos, peças e pesos do registro original',()=>{const base=[carga()];const edits=[{indice:0,itens:[{id:'a',x:50,y:0,z:0,rotacao:{x:90,y:0,z:0}},{id:'b',x:4000,y:0,z:0,rotacao:{x:0,y:0,z:0}}],passos:['b','a']}];const r=aplicarEdicaoMontagem(base,edits);expect(r[0].passos).toEqual(['b','a']);expect(r[0].itens[0].x).toBe(50);expect(r[0].peso).toBe(200);expect(r[0].usa).toBe(5950);expect(r[0].romaneio[0].madeira.compCaibro).toBe(0.6);expect(r[0].montagemManual).toBe(true);expect(base[0].itens[0].x).toBe(0);});
 it('recusa volumes omitidos, repetidos ou incluídos e sequência incompleta',()=>{const c=carga(),u={id:'a',x:0,y:0,z:0,rotacao:{x:0,y:0,z:0}};for(const itens of [[u],[u,u],[u,{...u,id:'c'}]])expect(()=>aplicarEdicaoMontagem([c],[{indice:0,itens,passos:['a','b']}])).toThrow();expect(()=>aplicarEdicaoMontagem([c],[{indice:0,itens:[u,{...u,id:'b'}],passos:['a','a']}])).toThrow();});
});
