import { describe, it, expect, vi, beforeEach } from 'vitest';
import { mockPrisma } from '@/testes/apoio/prisma';
vi.mock('@/lib/prisma',()=>({prisma:mockPrisma}));
import { valoresIniciaisInspecao, salvarInspecaoComPadroes } from '@/lib/padroes-inspecao';
beforeEach(()=>{vi.clearAllMocks();mockPrisma.padraoInspecao.findMany.mockResolvedValue([]);mockPrisma.planoPintura.findUnique.mockResolvedValue(null);});
describe('padrões por OP e tipo',()=>{
 it('pintura nova começa em Sa 2½ sem inventar medições',async()=>{const r=await valoresIniciaisInspecao('106','PINTURA');expect(r.limpeza).toBe('SA2.5');expect(r.abrasivo).toBe('Granalha');expect(r.demaos['1'].metodo).toBe('Airless');expect(r.prepTAmb).toBeUndefined();expect(r.laudo).toBeUndefined();});
 it('PLP vigente preenche o especificado; escolha da OP prevalece e registra divergência',async()=>{mockPrisma.planoPintura.findUnique.mockResolvedValue({grauLimpeza:'SA2.5',abrasivo:'Areia',demaos:[]});mockPrisma.padraoInspecao.findMany.mockResolvedValue([{campo:'limpeza',valor:'SA3'}]);const r=await valoresIniciaisInspecao('106','PINTURA');expect(r.limpeza).toBe('SA3');expect(r.abrasivo).toBe('Areia');expect(r.padroesInspecao.plp.limpeza).toBe('SA2.5');expect(mockPrisma.padraoInspecao.findMany).toHaveBeenCalledWith({where:{opNumero:'106',tipo:'PINTURA'}});});
 it('salvar Sa 3 guarda só a mudança; próxima criação usa o novo valor',async()=>{const rel={id:'r',opNumero:'106',tipo:'PINTURA',resultados:{limpeza:'SA2.5'}};await salvarInspecaoComPadroes(rel,{resultados:{limpeza:'SA3',prepTAmb:'27',laudo:'A',demaos:{1:{metodo:'Rolo',loteA:'ABC',visual:'Aprovado'}}}},'u');expect(mockPrisma.padraoInspecao.upsert).toHaveBeenCalledTimes(2);expect(mockPrisma.padraoInspecao.upsert.mock.calls.map(c=>c[0].create.campo)).toEqual(['limpeza','demaos.1.metodo']);expect(mockPrisma.auditLog.create).toHaveBeenCalled();mockPrisma.padraoInspecao.findMany.mockResolvedValue([{campo:'limpeza',valor:'SA3'}]);expect((await valoresIniciaisInspecao('106','PINTURA')).limpeza).toBe('SA3');});
 it('salvar relatório antigo sem alterar o campo não reverte o padrão',async()=>{await salvarInspecaoComPadroes({id:'r',opNumero:'106',tipo:'PINTURA',resultados:{limpeza:'SA2.5'}},{resultados:{limpeza:'SA2.5',prepTAmb:'30'}},'u');expect(mockPrisma.padraoInspecao.upsert).not.toHaveBeenCalled();});
 it('preserva escolha em branco e mantém OPs e tipos independentes',async()=>{await salvarInspecaoComPadroes({id:'r',opNumero:'107',tipo:'LP',resultados:{metodo:'A'}},{resultados:{metodo:''}},'u');expect(mockPrisma.padraoInspecao.upsert).toHaveBeenCalledWith(expect.objectContaining({where:{opNumero_tipo_campo:{opNumero:'107',tipo:'LP',campo:'metodo'}},update:expect.objectContaining({valor:null})}));mockPrisma.padraoInspecao.findMany.mockResolvedValue([{campo:'metodo',valor:null},{campo:'iluminacao',valor:'1800'}]);const r=await valoresIniciaisInspecao('107','LP');expect(r.metodo).toBeNull();expect(r.iluminacao).toBeUndefined();});
 // Vitor (23/09/2026): a junta soldada (EPS, RQS, processo, metal de adição, tipo de junta) faltava nos
 // relatórios da OP-102. É escolha da OBRA, como o penetrante: o próximo LP/EVS da mesma OP nasce com ela.
 it('LP e visual de solda lembram a junta soldada escolhida na OP',async()=>{
  const rel={id:'r',opNumero:'102',tipo:'LP',resultados:{}};
  await salvarInspecaoComPadroes(rel,{resultados:{eps:'EPS 002/2025',rqs:'RQPS 002/2025',processoSolda:'FCAW',metalAdicao:'E71T-1C',tipoJunta:'Ângulo',penetranteLote:'LT-1'}},'u');
  expect(mockPrisma.padraoInspecao.upsert.mock.calls.map(c=>c[0].create.campo).sort()).toEqual(['eps','metalAdicao','processoSolda','rqs','tipoJunta']);
  mockPrisma.padraoInspecao.findMany.mockResolvedValue([{campo:'eps',valor:'EPS 002/2025'},{campo:'rqs',valor:'RQPS 002/2025'},{campo:'processoSolda',valor:'FCAW'},{campo:'metalAdicao',valor:'E71T-1C'},{campo:'tipoJunta',valor:'Ângulo'}]);
  for (const tipo of ['LP','VISUAL_SOLDA']) expect(await valoresIniciaisInspecao('102',tipo)).toMatchObject({eps:'EPS 002/2025',rqs:'RQPS 002/2025',processoSolda:'FCAW',metalAdicao:'E71T-1C',tipoJunta:'Ângulo'});
 });
 it('não salva preferências se a gravação do relatório falhar',async()=>{mockPrisma.relatorioInspecao.update.mockRejectedValueOnce(new Error('falhou'));await expect(salvarInspecaoComPadroes({id:'r',opNumero:'1',tipo:'PINTURA',resultados:{}},{resultados:{limpeza:'SA3'}},'u')).rejects.toThrow('falhou');expect(mockPrisma.padraoInspecao.upsert).not.toHaveBeenCalled();});
});
