import { cabecalhoEmail } from "./email-layout";
import { escapeHtml as esc, textoParaHtml } from "./html";
import { fmtDataCronograma as data } from "./cronograma-envio";

export function gerarEmailCronograma({ cronograma: c, resumo, nomes, opcoes: o, remetente, referencia }) {
  const revisao = o.tipoEnvio === "REVISAO";
  const titulo = o.tipoEnvio === "INICIAL" ? "Cronograma da obra" : revisao ? `Cronograma revisado · ${o.revisao}` : "Atualização de andamento";
  const intro = o.tipoEnvio === "INICIAL" ? "Encaminhamos o cronograma da obra, com a programação das atividades e os arquivos para consulta." : revisao ? "Encaminhamos a revisão do cronograma. Confira abaixo as alterações comunicadas e a programação atual." : "Compartilhamos a posição atual do cronograma, com o andamento das atividades e as datas programadas.";
  const assunto = `${titulo} — OP ${c.opNumero || c.op?.numero || ""} · ${o.tituloCliente}`.replace(/[\r\n]+/g, " ");
  const campo = (nome, valor) => `<tr><td style="padding:6px 12px 6px 0;width:115px;font-size:12px;color:#6b8292;vertical-align:top;">${nome}</td><td style="padding:6px 0;font-size:13px;line-height:1.6;color:#23485f;font-weight:bold;">${esc(valor)}</td></tr>`;
  const box = (rotulo, valor) => `<td class="date" width="50%" style="padding:18px;background:#f1f6fa;vertical-align:top;"><p style="margin:0 0 8px;font-size:10px;letter-spacing:.6px;color:#617e91;">${rotulo}</p><p style="margin:0;font-size:22px;color:#173f57;">${data(valor)}</p></td>`;
  const html = `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>@media(max-width:520px){.outer{padding:0!important}.content{padding:22px 18px!important}.date{display:block!important;width:auto!important}.filename{word-break:break-word}}</style></head><body style="margin:0;background:#edf2f6;font-family:Arial,sans-serif;color:#18394f;">
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td class="outer" align="center" style="padding:24px 12px;">
  <!--[if mso]><table role="presentation" width="640"><tr><td><![endif]--><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="max-width:640px;background:white;border:1px solid #dce5ed;"><tr><td>${cabecalhoEmail(esc(titulo), `OP ${esc(c.opNumero || c.op?.numero || "")} · ${esc(o.tituloCliente)}`)}</td></tr>
  <tr><td class="content" style="padding:28px;"><p style="margin:0 0 12px;font-size:14px;line-height:1.8;">Olá,</p><p style="margin:0 0 18px;font-size:14px;line-height:1.8;">${intro}</p>
  ${o.mensagem ? `<p style="margin:0 0 20px;font-size:14px;line-height:1.8;">${textoParaHtml(o.mensagem)}</p>` : ""}
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin-bottom:19px;">${campo("Obra", o.tituloCliente)}${c.op?.cliente ? campo("Cliente", c.op.cliente) : ""}${c.op?.refCliente ? campo("Ref. do cliente", c.op.refCliente) : ""}${campo("Posição em", data(referencia))}</table>
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border:1px solid #dce6ed;"><tr>${box(revisao && resumo.fimBase ? "TÉRMINO NA LINHA DE BASE" : "INÍCIO PROGRAMADO", revisao && resumo.fimBase ? resumo.fimBase : resumo.inicio)}${box("TÉRMINO PROGRAMADO", resumo.fim)}</tr></table>
  ${o.tipoEnvio !== "INICIAL" ? `<p style="margin:13px 0 20px;font-size:12px;line-height:1.8;color:#657e8e;">${resumo.percentual == null ? "Avanço ponderado indisponível: atividades sem duração." : `Avanço do cronograma: <strong style="color:#146b8d;">${resumo.percentual}%</strong> · Ponderado por duração, sem duplicar tarefas-resumo.`}<br>${resumo.concluidas} de ${resumo.total} atividades concluídas.</p>` : ""}
  ${revisao ? `<h3 style="margin:24px 0 12px;font-size:16px;color:#173f57;">O que mudou nesta revisão</h3><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="padding:17px 18px;border-left:3px solid #F4801F;background:#faf7f2;font-size:13px;line-height:1.8;">${textoParaHtml(o.resumoAlteracoes)}</td></tr></table>` : ""}
  <h3 style="margin:26px 0 10px;font-size:16px;color:#173f57;">Arquivos anexos</h3><p style="margin:0 0 15px;font-size:12px;line-height:1.8;color:#6c8393;">Os dois arquivos acompanham este e-mail.</p>
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0">${[["PDF",nomes.pdf,"Cronograma completo para leitura e impressão."],["XML",nomes.xml,"Arquivo para integração ao Microsoft Project."]].map(([tipo,nome,desc]) => `<tr><td width="48" style="padding:13px 0;vertical-align:top;border-top:1px solid #e2eaf0;"><span style="font-size:10px;font-weight:bold;color:#2a627f;background:#eaf1f6;padding:6px;">${tipo}</span></td><td class="filename" style="padding:13px 0;border-top:1px solid #e2eaf0;font-size:12px;color:#23495f;"><strong>${esc(nome)}</strong><p style="font-size:11px;margin:5px 0 0;line-height:1.6;color:#738a98;">${desc}</p></td></tr>`).join("")}</table>
  <p style="margin:16px 0 0;font-size:11px;line-height:1.8;color:#748995;">Calendário: ${c.tipoDias === "DC" ? "dias corridos" : "segunda a sexta-feira"}, 8 horas por dia, sem feriados configurados.${revisao && resumo.fimBase ? " A linha de base permanece como referência de comparação." : ""}</p>
  <p style="margin:23px 0;font-size:13px;line-height:1.8;">Em caso de dúvida ou necessidade de alinhamento, responda a este e-mail.</p><p style="margin:0;font-size:13px;font-weight:bold;color:#183f57;">${esc(remetente || "Equipe de Planejamento")}</p><p style="margin:5px 0 0;font-size:12px;color:#6c8393;">Torg Metal · Estruturas Metálicas</p>
  </td></tr><tr><td style="padding:15px 28px;background:#eaf1f6;color:#6c8393;font-size:10px;line-height:1.7;">OP ${esc(c.opNumero || c.op?.numero || "")} · ${esc(titulo)} · ${data(referencia)}</td></tr></table><!--[if mso]></td></tr></table><![endif]--></td></tr></table></body></html>`;
  return { assunto, html };
}
