'use client';
import {Fragment,useState} from 'react';
import {DESTINOS_TERCEIRO,saldosTerceiro,marcaTerceiro} from '@/lib/terceiros-retorno';
import {itensRetornoSelecionados} from '@/lib/terceiros-distribuicao';
const field='border border-gray-300 rounded px-2 py-2 w-full text-sm';
export default function ReceberTerceiro({rom,onClose,onSalvo}){
 const saldos=saldosTerceiro(rom);
 const [linhas,setLinhas]=useState(()=>saldos.map(i=>({...i,qte:0,selecionada:false,dividir:false,distribuicao:[]})));
 const [destinoGeral,setDestinoGeral]=useState(()=>{const destinos=[...new Set(saldos.filter(l=>l.saldo>0).map(l=>l.destino))];return destinos.length===1&&DESTINOS_TERCEIRO.includes(destinos[0])?destinos[0]:''});
 const [data,setData]=useState(new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'}));
 const [obs,setObs]=useState(''),[erro,setErro]=useState(''),[busy,setBusy]=useState(false),[imp,setImp]=useState(null);
 const [chave]=useState(()=>crypto.randomUUID());
 const set=(n,k,v)=>setLinhas(a=>a.map((x,i)=>i===n?{...x,[k]:v}:x));
 const distribuir=(n,j,k,v)=>setLinhas(a=>a.map((x,i)=>i===n?{...x,distribuicao:x.distribuicao.map((d,b)=>b===j?{...d,[k]:v}:d)}:x));
 const selecionadas=linhas.filter(l=>l.selecionada);
 const elegiveis=linhas.filter(l=>l.saldo>0);
 const selecionarTodas=valor=>setLinhas(a=>a.map(l=>({...l,selecionada:valor&&l.saldo>0,qte:valor&&l.saldo>0?(Number(l.qte)>0?l.qte:l.saldo):l.qte})));
 let itens=[],problema='';
 if(selecionadas.length){try{itens=itensRetornoSelecionados(linhas,destinoGeral)}catch(e){problema=e.message}}
 async function importar(file){if(!file)return;setBusy(true);setErro('');setImp(null);setLinhas(a=>a.map(l=>({...l,qte:0,selecionada:false,dividir:false,distribuicao:[]})));try{const f=new FormData();f.append('arquivo',file);const r=await fetch('/api/expedicao/terceiros/'+rom.id+'/importar-retorno',{method:'POST',body:f});const j=await r.json();if(!r.ok)throw Error(j.error);setImp(j);}catch(e){setErro(e.message)}finally{setBusy(false)}}
 function aplicar(){setLinhas(a=>a.map(x=>{const l=imp.linhas.find(l=>!l.erro&&marcaTerceiro(l.marca)===marcaTerceiro(x.marca));return {...x,qte:l?l.qte:0,selecionada:Boolean(l),dividir:false,distribuicao:[]}}));setImp({...imp,aplicado:true})}
 async function salvar(e){e.preventDefault();if(problema||!itens.length){setErro(problema||'Selecione ao menos uma marca recebida.');return;}setBusy(true);setErro('');try{const r=await fetch('/api/expedicao/terceiros/'+rom.id+'/retorno',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data,observacao:obs,chave,...(imp?.aplicado?{documentoHash:imp.documentoHash}:{}),itens})});const j=await r.json();if(!r.ok)throw Error(j.error);onSalvo(j.romaneio)}catch(e){setErro(e.message);setBusy(false)}}
 const quantidade=selecionadas.reduce((a,l)=>a+(Number(l.qte)||0),0);
 return <div className="fixed inset-0 z-[70] bg-black/40 overflow-y-auto p-4" role="dialog" aria-modal="true" aria-label="Registrar retorno"><form onSubmit={salvar} className="bg-white rounded-xl shadow-xl max-w-5xl mx-auto my-6 text-torg-dark"><header className="p-5 border-b flex justify-between"><div><h2 className="font-bold text-lg">Registrar retorno · RT-{rom.numero}</h2><p className="text-sm text-gray-500">OP {rom.opRefNumero||'não informada'} · {rom.terceiroNome}</p></div><button type="button" onClick={onClose} disabled={busy}>Fechar</button></header><div className="p-5 space-y-4">
 {erro&&<p role="alert" className="bg-red-50 text-red-700 p-3 rounded">{erro}</p>}
 <p className="text-sm text-gray-600">Escolha o setor uma vez para todo o retorno. Separe apenas as peças que precisam de outro destino. O saldo vencido continua em atraso até o retorno completo.</p>
 <label className="block border border-dashed rounded-lg p-4 text-sm">Importar planilha ou PDF · até 4 MB<input className="block mt-2" type="file" accept=".xlsx,.xls,.csv,.pdf" disabled={busy} onChange={e=>importar(e.target.files?.[0])}/><span className="block text-xs text-gray-500 mt-2">Planilha: OP, Marca e Quantidade. A leitura do PDF será apresentada para sua conferência.</span></label>
 {imp&&<section className="border rounded-lg p-3 space-y-2"><h3 className="font-semibold">Conferir documento: {imp.nome}</h3>{imp.duplicado&&<p className="text-red-700">Este documento já foi recebido nesta remessa.</p>}<div className="max-h-52 overflow-auto"><table className="w-full text-xs"><thead><tr><th>OP</th><th>Marca</th><th>Recebido</th><th>Conferência</th></tr></thead><tbody>{imp.linhas.map((l,i)=><tr key={i} className={l.erro?'text-red-700':''}><td>{l.op||'—'}</td><td>{l.marca}</td><td>{l.qte}</td><td>{l.erro||'Dentro do saldo'}</td></tr>)}</tbody></table></div><button type="button" className="text-blue-700 border rounded p-2 disabled:opacity-40" disabled={busy||imp.duplicado||imp.linhas.some(l=>l.erro)} onClick={aplicar}>{imp.aplicado?'Quantidades preenchidas abaixo':'Usar quantidades conferidas'}</button><p className="text-xs text-gray-500">Corrija as linhas destacadas no documento ou preencha manualmente. Nenhuma baixa é feita ao importar.</p></section>}
 <div className="bg-sky-50 border border-sky-100 rounded-lg p-4 flex flex-wrap justify-between items-center gap-4">
  <div><label className="flex flex-wrap items-center gap-3 font-semibold text-sm">Destino de todo o retorno<select aria-label="Destino de todo o retorno" required value={destinoGeral} disabled={busy} className={field+' !w-auto min-w-[180px]'} onChange={e=>setDestinoGeral(e.target.value)}><option value="">Escolher setor</option>{DESTINOS_TERCEIRO.map(d=><option key={d}>{d}</option>)}</select></label><p className="text-xs text-gray-500 mt-2">Aplicado a todas as marcas recebidas, exceto às quantidades separadas abaixo.</p></div>
  <button type="button" disabled={busy||!elegiveis.length} className="text-blue-700 border bg-white rounded px-3 py-2 text-sm" onClick={()=>selecionarTodas(true)}>Selecionar todas as marcas</button>
 </div>
 <div className="overflow-auto"><table className="w-full text-sm min-w-[740px]"><thead className="bg-gray-50 text-xs"><tr><th className="p-2"><input type="checkbox" aria-label="Selecionar todas as marcas" disabled={busy||!elegiveis.length} checked={Boolean(elegiveis.length)&&selecionadas.length===elegiveis.length} ref={el=>{if(el)el.indeterminate=selecionadas.length>0&&selecionadas.length<elegiveis.length}} onChange={e=>selecionarTodas(e.target.checked)}/></th>{['Marca','Saldo no terceiro','Receber agora','Destino aplicado',''].map((x,n)=><th className="p-2 text-left" key={n}>{x}</th>)}</tr></thead><tbody>{linhas.map((l,i)=>{
 const separado=l.distribuicao.reduce((a,d)=>a+Number(d.qte||0),0);
 return <Fragment key={l.marca}><tr className={l.selecionada?'bg-sky-50/50 border-b':'border-b'}>
 <td className="p-2"><input type="checkbox" aria-label={'Selecionar '+l.marca} checked={l.selecionada} disabled={busy||!l.saldo} onChange={e=>{const checked=e.target.checked;setLinhas(a=>a.map((x,n)=>n===i?{...x,selecionada:checked,qte:checked&&!(Number(x.qte)>0)?x.saldo:x.qte}:x))}}/></td>
 <td className="p-2 font-semibold">{l.marca}</td><td className="p-2">{l.saldo==null?'Conferir histórico':`${l.saldo} peças`}<span className="block text-xs text-gray-500 mt-1">Enviado: {l.enviada??'—'} · Já voltou: {l.voltou}</span></td>
 <td className="p-2"><input aria-label={'Receber '+l.marca} type="number" min="1" max={l.saldo??0} step="1" value={l.qte} disabled={busy||!l.selecionada} className={field+' max-w-[95px]'} onChange={e=>set(i,'qte',e.target.value)}/></td>
 <td className="p-2 text-gray-500">{l.selecionada?(destinoGeral||'Escolher acima'):'—'}</td><td className="p-2">{l.selecionada&&<button type="button" disabled={busy} aria-expanded={l.dividir} className="text-blue-700 text-xs whitespace-nowrap" onClick={()=>setLinhas(a=>a.map((x,n)=>n===i?{...x,dividir:!x.dividir,distribuicao:!x.dividir?[{qte:0,destino:''}]:[]}:x))}>{l.dividir?'Usar destino geral':'Separar para outros setores'}</button>}</td></tr>
 {l.selecionada&&l.dividir&&<tr className="bg-sky-50/50 border-b"><td colSpan={6} className="p-3 pl-10"><div className="border-l-2 border-sky-200 pl-4 space-y-2">{l.distribuicao.map((d,j)=><div key={j} className="flex flex-wrap items-center gap-2 text-xs"><span>Separar</span><input aria-label={`Quantidade ${l.marca} destino ${j+1}`} type="number" min="1" step="1" max={l.qte} required className={field+' max-w-[85px]'} value={d.qte} disabled={busy} onChange={e=>distribuir(i,j,'qte',e.target.value)}/><span>peças para</span><select aria-label={`Setor ${l.marca} destino ${j+1}`} required className={field+' !w-auto min-w-[150px]'} value={d.destino} disabled={busy} onChange={e=>distribuir(i,j,'destino',e.target.value)}><option value="">Escolher outro setor</option>{DESTINOS_TERCEIRO.map(v=><option key={v} disabled={v===destinoGeral}>{v}</option>)}</select><button type="button" aria-label={`Remover ${l.marca} destino ${j+1}`} disabled={busy} onClick={()=>set(i,'distribuicao',l.distribuicao.filter((_,n)=>n!==j))}>×</button></div>)}<div className="flex flex-wrap gap-4 items-center"><span className="text-xs text-gray-500">{Math.max(0,Number(l.qte||0)-separado)} peças seguem para {destinoGeral||'o destino geral'}</span><button type="button" disabled={busy||l.distribuicao.length>=DESTINOS_TERCEIRO.length-1} className="text-blue-700 text-xs" onClick={()=>set(i,'distribuicao',[...l.distribuicao,{qte:0,destino:''}])}>+ Separar para outro setor</button></div></div></td></tr>}
 </Fragment>})}</tbody></table></div>
 {problema&&<p role="status" className="text-amber-800 bg-amber-50 rounded p-3 text-sm">{problema}</p>}
 <div className="grid sm:grid-cols-2 gap-4"><label className="text-sm">Data do retorno<input type="date" required value={data} onChange={e=>setData(e.target.value)} className={field}/></label><label className="text-sm">Observação<input maxLength={1000} value={obs} onChange={e=>setObs(e.target.value)} className={field}/></label></div>
 </div><footer className="p-5 border-t flex justify-between items-center"><span className="text-sm">{selecionadas.length} marcas selecionadas · {quantidade} peças neste retorno</span><button disabled={busy||!quantidade||Boolean(problema)} className="bg-torg-dark text-white rounded-lg px-5 py-3 disabled:opacity-50">{busy?'Processando…':'Confirmar recebimento'}</button></footer></form></div>
}
