'use client';
import {useState} from 'react';
import {DESTINOS_TERCEIRO,saldosTerceiro,marcaTerceiro} from '@/lib/terceiros-retorno';
const field='border border-gray-300 rounded px-2 py-2 w-full text-sm';
export default function ReceberTerceiro({rom,onClose,onSalvo}){
 const saldos=saldosTerceiro(rom);
 const [linhas,setLinhas]=useState(()=>saldos.map(i=>({...i,qte:0,destino:i.destino||'',dividir:false,distribuicao:[]})));
 const [data,setData]=useState(new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'}));
 const [obs,setObs]=useState(''),[erro,setErro]=useState(''),[busy,setBusy]=useState(false),[imp,setImp]=useState(null);
 const [chave]=useState(()=>crypto.randomUUID());
 const set=(n,k,v)=>setLinhas(a=>a.map((x,i)=>i===n?{...x,[k]:v}:x));
 const distribuir=(n,j,k,v)=>setLinhas(a=>a.map((x,i)=>i===n?{...x,distribuicao:x.distribuicao.map((d,b)=>b===j?{...d,[k]:v}:d)}:x));
 const problema=linhas.filter(l=>Number(l.qte)>0&&l.dividir).map(l=>{
  const total=l.distribuicao.reduce((a,d)=>a+Number(d.qte||0),0);
  if(total!==Number(l.qte))return `Distribua exatamente ${l.qte} peças da marca ${l.marca}; foram distribuídas ${total}.`;
  if(l.distribuicao.some(d=>!d.destino||!Number.isInteger(Number(d.qte))||Number(d.qte)<=0))return `Informe quantidade e setor para cada destino de ${l.marca}.`;
  if(new Set(l.distribuicao.map(d=>d.destino)).size!==l.distribuicao.length)return `Agrupe as quantidades de ${l.marca} que vão para o mesmo setor.`;
  return '';
 }).find(Boolean);
 async function importar(file){if(!file)return;setBusy(true);setErro('');setImp(null);setLinhas(a=>a.map(l=>({...l,qte:0,dividir:false,distribuicao:[]})));try{const f=new FormData();f.append('arquivo',file);const r=await fetch('/api/expedicao/terceiros/'+rom.id+'/importar-retorno',{method:'POST',body:f});const j=await r.json();if(!r.ok)throw Error(j.error);setImp(j);}catch(e){setErro(e.message)}finally{setBusy(false)}}
 function aplicar(){setLinhas(a=>a.map(x=>{const l=imp.linhas.find(l=>!l.erro&&marcaTerceiro(l.marca)===marcaTerceiro(x.marca));return {...x,qte:l?l.qte:0,dividir:false,distribuicao:[]}}));setImp({...imp,aplicado:true})}
 async function salvar(e){e.preventDefault();if(problema){setErro(problema);return;}setBusy(true);setErro('');try{const r=await fetch('/api/expedicao/terceiros/'+rom.id+'/retorno',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data,observacao:obs,chave,...(imp?.aplicado?{documentoHash:imp.documentoHash}:{}),itens:linhas.filter(l=>Number(l.qte)>0).flatMap(l=>(l.dividir?l.distribuicao:[{qte:l.qte,destino:l.destino}]).map(d=>({marca:l.marca,qte:Number(d.qte),destino:d.destino})))})});const j=await r.json();if(!r.ok)throw Error(j.error);onSalvo(j.romaneio)}catch(e){setErro(e.message);setBusy(false)}}
 const quantidade=linhas.reduce((a,l)=>a+(Number(l.qte)||0),0);
 return <div className="fixed inset-0 z-[70] bg-black/40 overflow-y-auto p-4" role="dialog" aria-modal="true" aria-label="Registrar retorno"><form onSubmit={salvar} className="bg-white rounded-xl shadow-xl max-w-5xl mx-auto my-6 text-torg-dark"><header className="p-5 border-b flex justify-between"><div><h2 className="font-bold text-lg">Registrar retorno · RT-{rom.numero}</h2><p className="text-sm text-gray-500">OP {rom.opRefNumero||'não informada'} · {rom.terceiroNome}</p></div><button type="button" onClick={onClose} disabled={busy}>Fechar</button></header><div className="p-5 space-y-4">
 {erro&&<p role="alert" className="bg-red-50 text-red-700 p-3 rounded">{erro}</p>}
 <p className="text-sm text-gray-600">Informe somente o que chegou. O saldo continua no terceiro. Você pode dividir a mesma marca entre setores. Se o prazo venceu, o saldo permanece em atraso até o retorno completo.</p>
 <label className="block border border-dashed rounded-lg p-4 text-sm">Importar planilha ou PDF · até 4 MB<input className="block mt-2" type="file" accept=".xlsx,.xls,.csv,.pdf" disabled={busy} onChange={e=>importar(e.target.files?.[0])}/><span className="block text-xs text-gray-500 mt-2">Planilha: OP, Marca e Quantidade. A leitura do PDF será apresentada para sua conferência.</span></label>
 {imp&&<section className="border rounded-lg p-3 space-y-2"><h3 className="font-semibold">Conferir documento: {imp.nome}</h3>{imp.duplicado&&<p className="text-red-700">Este documento já foi recebido nesta remessa.</p>}<div className="max-h-52 overflow-auto"><table className="w-full text-xs"><thead><tr><th>OP</th><th>Marca</th><th>Recebido</th><th>Conferência</th></tr></thead><tbody>{imp.linhas.map((l,i)=><tr key={i} className={l.erro?'text-red-700':''}><td>{l.op||'—'}</td><td>{l.marca}</td><td>{l.qte}</td><td>{l.erro||'Dentro do saldo'}</td></tr>)}</tbody></table></div><button type="button" className="text-blue-700 border rounded p-2 disabled:opacity-40" disabled={busy||imp.duplicado||imp.linhas.some(l=>l.erro)} onClick={aplicar}>{imp.aplicado?'Quantidades preenchidas abaixo':'Usar quantidades conferidas'}</button><p className="text-xs text-gray-500">Corrija as linhas destacadas no documento ou preencha manualmente. Nenhuma baixa é feita ao importar.</p></section>}
 <button type="button" className="text-blue-700 text-sm" disabled={busy} onClick={()=>setLinhas(a=>a.map(l=>({...l,qte:l.saldo??0,dividir:false,distribuicao:[]})))}>Preencher todo o saldo</button>
 <div className="overflow-auto"><table className="w-full text-sm min-w-[620px]"><thead className="bg-gray-50 text-xs"><tr>{['Marca','Enviado','Já voltou','Saldo','Receber agora','Destino na Torg'].map(x=><th className="p-2 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{linhas.map((l,i)=><tr key={l.marca} className="border-b"><td className="p-2 font-semibold">{l.marca}</td><td>{l.enviada??'—'}</td><td>{l.voltou}</td><td>{l.saldo??'Conferir histórico'}</td><td className="p-2"><input aria-label={'Receber '+l.marca} type="number" min="0" max={l.saldo??0} step="1" value={l.qte} disabled={busy||l.saldo==null} className={field} onChange={e=>set(i,'qte',e.target.value)}/></td><td className="p-2 min-w-[290px]">
 {!l.dividir&&<select aria-label={'Destino '+l.marca} required={Number(l.qte)>0} value={l.destino} className={field} disabled={busy} onChange={e=>set(i,'destino',e.target.value)}><option value="">Escolher setor</option>{DESTINOS_TERCEIRO.map(d=><option key={d}>{d}</option>)}</select>}
 <label className="flex items-center gap-2 text-xs my-2"><input type="checkbox" checked={l.dividir} disabled={busy} onChange={e=>{const checked=e.target.checked;setLinhas(a=>a.map((x,n)=>n===i?{...x,dividir:checked,distribuicao:checked?[{qte:Number(x.qte)||0,destino:x.destino},{qte:0,destino:''}]:[]}:x))}}/>Dividir {l.marca} entre setores</label>
 {l.dividir&&<div className="bg-slate-50 border rounded-lg p-2 space-y-2">{l.distribuicao.map((d,j)=><div key={j} className="flex items-center gap-2"><input aria-label={`Quantidade ${l.marca} destino ${j+1}`} type="number" min="1" step="1" max={l.qte} required={Number(l.qte)>0} className={field+' max-w-[76px]'} value={d.qte} disabled={busy||!Number(l.qte)} onChange={e=>distribuir(i,j,'qte',e.target.value)}/><select aria-label={`Setor ${l.marca} destino ${j+1}`} required={Number(l.qte)>0} className={field} value={d.destino} disabled={busy||!Number(l.qte)} onChange={e=>distribuir(i,j,'destino',e.target.value)}><option value="">Escolher setor</option>{DESTINOS_TERCEIRO.map(v=><option key={v}>{v}</option>)}</select><button type="button" aria-label={`Remover ${l.marca} destino ${j+1}`} disabled={busy||l.distribuicao.length<=1} onClick={()=>set(i,'distribuicao',l.distribuicao.filter((_,n)=>n!==j))}>×</button></div>)}<button type="button" disabled={busy||l.distribuicao.length>=DESTINOS_TERCEIRO.length} className="text-blue-700 text-xs" onClick={()=>set(i,'distribuicao',[...l.distribuicao,{qte:0,destino:''}])}>+ Adicionar setor</button><p className="text-xs font-medium">Distribuído: {l.distribuicao.reduce((a,d)=>a+Number(d.qte||0),0)} de {Number(l.qte)||0} peças</p></div>}
 <p className="text-xs text-gray-500 mt-2">Saldo no terceiro após este retorno: {l.saldo==null?'—':Math.max(0,l.saldo-Number(l.qte||0))} peças</p>
 </td></tr>)}</tbody></table></div>
 {problema&&<p role="status" className="text-amber-800 bg-amber-50 rounded p-3 text-sm">{problema}</p>}
 <div className="grid sm:grid-cols-2 gap-4"><label className="text-sm">Data do retorno<input type="date" required value={data} onChange={e=>setData(e.target.value)} className={field}/></label><label className="text-sm">Observação<input maxLength={1000} value={obs} onChange={e=>setObs(e.target.value)} className={field}/></label></div>
 </div><footer className="p-5 border-t flex justify-between items-center"><span className="text-sm">{quantidade} peças neste retorno</span><button disabled={busy||!quantidade||Boolean(problema)} className="bg-torg-dark text-white rounded-lg px-5 py-3 disabled:opacity-50">{busy?'Processando…':'Confirmar recebimento'}</button></footer></form></div>
}
