import {it,expect,vi,beforeEach} from 'vitest';
import {mockPrisma} from '@/testes/apoio/prisma';
vi.mock('@/lib/prisma',()=>({prisma:mockPrisma}));
vi.mock('@/lib/session',()=>({requireRole:vi.fn().mockResolvedValue({id:'u'}),getSession:vi.fn().mockResolvedValue(null)}));
vi.mock('@/lib/email',()=>({sendEmail:vi.fn().mockResolvedValue({ok:true})}));
vi.mock('@/lib/email-layout',()=>({cabecalhoEmail:()=>''}));
vi.mock('@/lib/databook-assinaturas',()=>({baseUrlDe:()=> 'http://localhost'}));
vi.mock('@/lib/assinatura-cadastro',()=>({assinaturaDoEmail:vi.fn().mockResolvedValue(null)}));
vi.mock('@/lib/relatorio-inspecao',()=>({vincularNoDataBook:vi.fn().mockResolvedValue({}),proximoNumero:vi.fn().mockResolvedValue(1)}));
vi.mock('@/lib/importar-procedimentos',()=>({procedimentoDoTipo:vi.fn().mockResolvedValue(null)}));
vi.mock('@/lib/relatorio-dimensional',()=>({procedimentoTolerancia:vi.fn().mockResolvedValue(null)}));
vi.mock('@/lib/relatorio-arquivo',()=>({arquivarRelatorioNaObra:vi.fn().mockResolvedValue({ok:true})}));
import {POST as criar} from '@/app/api/qualidade/inspecoes/dimensional/route';
import {GET as abrir,PATCH as salvar} from '@/app/api/campo/relatorios/[id]/route';
import {POST as enviar} from '@/app/api/qualidade/inspecoes/[id]/assinatura/route';
import {POST as assinar} from '@/app/api/assinar/[token]/route';
import {gerarPDFdoRelatorio} from '@/lib/relatorio-render';
import {extractText} from 'unpdf';
let rel,envio,assinaturas;
const req=body=>new Request('http://localhost',{method:'POST',headers:{'x-forwarded-for':'127.0.0.1'},body:JSON.stringify(body)});
beforeEach(()=>{vi.clearAllMocks();assinaturas=[];envio=null;mockPrisma.oP.findFirst.mockResolvedValue(null);mockPrisma.planoPintura.findUnique.mockResolvedValue(null);mockPrisma.user.findFirst.mockResolvedValue(null);mockPrisma.auditLog.create.mockResolvedValue({});mockPrisma.relatorioInspecao.create.mockImplementation(async({data})=>(rel={id:'r',...data}));mockPrisma.relatorioInspecao.findUnique.mockImplementation(async()=>rel);mockPrisma.relatorioInspecao.update.mockImplementation(async({data})=>(rel={...rel,...data}));mockPrisma.fotoInspecao.findMany.mockResolvedValue([]);mockPrisma.envioAssinatura.create.mockImplementation(async({data})=>(envio={id:'envio',status:'PENDENTE',...data}));mockPrisma.envioAssinatura.update.mockImplementation(async({data})=>(envio={...envio,...data}));mockPrisma.assinaturaDocumento.findMany.mockImplementation(async()=>assinaturas);mockPrisma.assinaturaDocumento.create.mockImplementation(async({data})=>{const a={id:'a'+assinaturas.length,assinadoEm:null,...data};assinaturas.push(a);return a;});mockPrisma.assinaturaDocumento.findUnique.mockImplementation(async({where})=>({...assinaturas.find(a=>a.token===where.token),envio}));mockPrisma.assinaturaDocumento.findFirst.mockResolvedValue(null);mockPrisma.assinaturaDocumento.count.mockImplementation(async()=>assinaturas.filter(a=>!a.assinadoEm).length);mockPrisma.assinaturaDocumento.update.mockImplementation(async({where,data})=>{const a=assinaturas.find(a=>a.id===where.id);Object.assign(a,data);return a;});});
it.each(['PINTURA','VISUAL_SOLDA'])('cria, preenche, reabre, gera PDF e coleta todas as assinaturas de %s',async tipo=>{
 const pecasInformadas=[{marca:'P1',quantidade:212},{marca:'P2',quantidade:16}];
 expect((await criar(req({opNumero:'106',tipo,escopo:'AVULSAS',marcas:['P1','P2'],pecasInformadas}))).status).toBe(200);
 expect((await abrir(null,{params:{id:'r'}})).status).toBe(200);
 pecasInformadas[0].quantidade=200;
 expect((await salvar(req({pecasInformadas,condicoes:{poeira:'N/A',salinidade:'N/A',pullOffValor:'7',iluminacao:'600',rugLeituras:[50,51,52,53,54]},resultadoInspecao:'APROVADO'}),{params:{id:'r'}})).status).toBe(200);
 const reaberto=(await (await abrir(null,{params:{id:'r'}})).json()).relatorio;
 expect(reaberto.resultados).toMatchObject({quantidade:'216',poeira:'N/A',salinidade:'N/A',pullOffValor:'7'});
 const pdf=await gerarPDFdoRelatorio({rel:reaberto});expect((await extractText(new Uint8Array(pdf),{mergePages:true})).text).toContain('216');
 expect((await enviar(req({destinatarios:[{nome:'Inspetor Teste',email:'inspetor@example.test'},{nome:'Cliente Teste',email:'cliente@example.test'}]}),{params:{id:'r'}})).status).toBe(200);
 expect((await salvar(req({pecasInformadas}),{params:{id:'r'}})).status).toBe(409);
 expect((await assinar(req({}),{params:{token:assinaturas[0].token}})).status).toBe(200);
 expect(envio.status).not.toBe('CONCLUIDO');
 expect((await assinar(req({}),{params:{token:assinaturas[1].token}})).status).toBe(200);
 expect(envio.status).toBe('CONCLUIDO');
});
it('permite tentar novamente um convite que falhou sem duplicar assinantes',async()=>{
 const {sendEmail}=await import('@/lib/email');
 rel={id:'r',codigo:'RIP-106-TESTE',tipo:'PINTURA',opNumero:'106',marcas:['P1'],resultados:{quantidade:'2'},linhas:[],equipamentos:[]};
 const body={destinatarios:[{nome:'Teste',email:'teste@example.test'}]};
 sendEmail.mockResolvedValueOnce({ok:false,error:'Falha simulada'}).mockResolvedValueOnce({ok:false,error:'Falha simulada'});
 const primeira=await enviar(req(body),{params:{id:'r'}});expect((await primeira.json()).enviados).toBe(0);
 const token=assinaturas[0].token;
 const segunda=await enviar(req(body),{params:{id:'r'}});expect((await segunda.json()).enviados).toBe(1);
 expect(assinaturas).toHaveLength(1);expect(assinaturas[0].token).toBe(token);
});
