import * as T from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {mergeGeometries} from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import {configurarLuzesIfc} from '../../lib/ifc-visual.js';
const host=document.querySelector('#view'),panel=document.querySelector('#panel'),status=document.querySelector('#status');
const scene=new T.Scene();scene.background=new T.Color('#ffffff');configurarLuzesIfc(T,scene,false,true);
const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.localClippingEnabled=true;host.appendChild(renderer.domElement);
const cam=new T.PerspectiveCamera(38,1,.01,2000),controls=new OrbitControls(cam,renderer.domElement);controls.addEventListener('change',draw);
const group=new T.Group();scene.add(group);let data,mode='ligacao',parts=[],overview=[],detail=[],center,fullBox, timer,selected=null;
function draw(){renderer.render(scene,cam);}
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);cam.aspect=w/h;cam.updateProjectionMatrix();draw();}new ResizeObserver(resize).observe(host);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function frame(box){const c=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3()).length();cam.position.copy(c).add(new T.Vector3(.85,.6,.9).normalize().multiplyScalar(size*1.45));controls.target.copy(c);cam.near=Math.max(.005,size/10000);cam.far=size*100+100;cam.updateProjectionMatrix();controls.update();draw();}
const ctr=i=>new T.Vector3().fromArray(i.min).add(new T.Vector3().fromArray(i.max)).multiplyScalar(.5);
function mat(color){return new T.MeshPhongMaterial({color,side:T.DoubleSide,shininess:14,specular:0x1e2833});}
function meshFor(i){const g=parts[i.geo].clone().applyMatrix4(new T.Matrix4().fromArray(i.m));const m=new T.Mesh(g,mat(new T.Color().setRGB(...i.color,T.SRGBColorSpace)));m.userData=i;return m;}
function clear(){for(const m of [...group.children])group.remove(m);selected=null;clearInterval(timer);}
function addEdges(m){const e=new T.LineSegments(new T.EdgesGeometry(m.geometry,25),new T.LineBasicMaterial({color:0x31495a,transparent:true,opacity:.38,clippingPlanes:m.material.clippingPlanes}));m.add(e);}
function overviewBuild(){const groups=new Map();fullBox=new T.Box3();for(const i of data.items)fullBox.union(new T.Box3(new T.Vector3().fromArray(i.min),new T.Vector3().fromArray(i.max)));
const c=fullBox.getCenter(new T.Vector3());const bounds=fullBox.getSize(new T.Vector3());const axis=bounds.x>bounds.z?'x':'z';
for(const i of data.items){const pos=ctr(i)[axis],stage=Math.min(3,Math.floor((pos-fullBox.min[axis])/bounds[axis]*4));i.stage=stage;const k=`${stage}|${i.color.join(',')}`;if(!groups.has(k))groups.set(k,{stage,color:i.color,gs:[]});groups.get(k).gs.push(parts[i.geo].clone().applyMatrix4(new T.Matrix4().fromArray(i.m)));}
for(const {stage,color,gs} of groups.values()){const g=mergeGeometries(gs);gs.forEach(x=>x.dispose());const m=new T.Mesh(g,mat(new T.Color().setRGB(...color,T.SRGBColorSpace)));m.userData={stage,base:m.material.color.clone()};overview.push(m);}
}
function detailBuild(){const bolt=data.items.find(i=>i.id===845);center=ctr(bolt);const half=.43;
// Recorte espacial de demonstração: proximidade não certifica pertença à ligação.
const crop=new T.Box3(center.clone().addScalar(-half),center.clone().addScalar(half));
const nearby=data.items.filter(i=>!/^EXISTENTE$/i.test(i.name)&&crop.intersectsBox(new T.Box3(new T.Vector3().fromArray(i.min),new T.Vector3().fromArray(i.max))));
for(const i of nearby){const m=meshFor(i);const type=/fastener/i.test(i.type)?'fixador':/plate/i.test(i.type)?'chapa':'perfil';const c=ctr(i);const delta=c.clone().sub(center);delta.clampScalar(-.3,.3);if(delta.length()<.03)delta.set(.1,0,.1);delta.normalize();
m.userData={...i,kind:type,delta:delta.multiplyScalar(type==='fixador'?.42:type==='chapa'?.26:.15)};
m.material.clippingPlanes=[new T.Plane(new T.Vector3(1,0,0),-crop.min.x),new T.Plane(new T.Vector3(-1,0,0),crop.max.x),new T.Plane(new T.Vector3(0,1,0),-crop.min.y),new T.Plane(new T.Vector3(0,-1,0),crop.max.y),new T.Plane(new T.Vector3(0,0,1),-crop.min.z),new T.Plane(new T.Vector3(0,0,-1),crop.max.z)];m.userData.constants=m.material.clippingPlanes.map(p=>p.constant);if(type!=='fixador')addEdges(m);detail.push(m);}
}
function explode(value){const n=Number(value)/100;for(const m of detail){m.position.copy(m.userData.delta).multiplyScalar(n);m.material.clippingPlanes.forEach((p,k)=>p.constant=m.userData.constants[k]-p.normal.dot(m.position));}document.querySelector('#value').textContent=`${value}%`;draw();}
function ligacao(){detail.forEach(m=>group.add(m));const counts={};detail.forEach(m=>counts[m.userData.kind]=(counts[m.userData.kind]||0)+1);panel.innerHTML=`<h2>Explore a ligação</h2><p>Região do contraventamento <strong>T89C87 / T89C94 / T89C89</strong>, próxima ao elemento IFC #845.</p><label for="explode">Separação visual <strong id="value">0%</strong></label><input id="explode" type="range" min="0" max="100" value="0"><div class="controls"><button id="closed">Montada</button><button id="open">Explodida</button><button id="plate">Chapa inteira</button></div><div class="item">Perfis, chapas e fixadores do IFC original · geometrias recortadas para visualizar a região</div><p class="note"><strong>Furos ausentes no IFC:</strong> as cinco chapas deste recorte foram exportadas sem contornos internos de furação. A explosão não consegue revelar furos que não estão na geometria.</p><p class="note">Recorte por proximidade. A separação é ilustrativa: não define ordem de desmontagem nem certifica quais peças pertencem à ligação. Fixadores não foram decompostos em porca e arruela quando vieram unidos no IFC.</p><p class="muted">Clique numa peça para consultar sua identificação real.</p><div id="picked" aria-live="polite"></div>`;
const input=document.querySelector('#explode'); const restore=()=>{for(const m of [...group.children])group.remove(m);detail.forEach(m=>group.add(m));frame(new T.Box3(center.clone().addScalar(-.65),center.clone().addScalar(.65)));status.textContent='Ligação · peças reais em um recorte de 0,86 m';};input.oninput=()=>{restore();explode(input.value);}; document.querySelector('#plate').onclick=()=>{for(const m of [...group.children])group.remove(m);const source=data.items.find(i=>i.id===1034);const plate=meshFor(source);addEdges(plate);group.add(plate);frame(new T.Box3().setFromObject(plate));status.textContent='T89C150 · chapa inteira, sem recorte e sem alteração geométrica';document.querySelector('#picked').textContent='IFC #1034 · CHAPA NÓ · T89C150 · sólido extrudado com contorno externo, sem furos nesta exportação';};document.querySelector('#closed').onclick=()=>{restore();input.value=0;explode(0);};document.querySelector('#open').onclick=()=>{restore();input.value=100;explode(100);};explode(0);frame(new T.Box3(center.clone().addScalar(-.65),center.clone().addScalar(.65)));status.textContent='Ligação · peças reais em um recorte de 0,86 m';}
function stage(v){for(const m of overview){m.visible=true;m.material.color.copy(m.userData.base);const future=m.userData.stage>=v;m.material.transparent=future;m.material.opacity=future?.045:1;m.material.depthWrite=!future;}document.querySelector('#step').textContent=v==='0'?'Estrutura de referência':`${v} de 4 trechos apresentados`;document.querySelectorAll('[data-step]').forEach(b=>b.classList.toggle('active',b.dataset.step===String(v)));draw();}
function montagem(){overview.forEach(m=>group.add(m));panel.innerHTML=`<h2>A obra por etapas</h2><p>Avance para ver os trechos surgirem na posição real do projeto.</p><p class="tag">ORDEM ILUSTRATIVA</p><div class="controls">${[0,1,2,3,4].map(n=>`<button data-step="${n}">${n===0?'Início':n}</button>`).join('')}</div><strong id="step"></strong><div class="controls"><button id="play">Reproduzir etapas</button></div><p class="note">Os quatro trechos foram divididos por posição no modelo para demonstrar a interação. Não são um plano de montagem: apoios, estabilidade, içamento e ligações temporárias não foram analisados.</p><p>Na proposta final, as etapas viriam do plano aprovado da Engenharia, com suas datas e conjuntos associados.</p>`;document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{clearInterval(timer);stage(b.dataset.step);});document.querySelector('#play').onclick=()=>{clearInterval(timer);let v=0;stage('0');timer=setInterval(()=>{stage(String(++v));if(v>=4)clearInterval(timer);},1500);};stage('2');frame(fullBox);status.textContent='Sequência ilustrativa · geometria original, sem datas ou liberações fictícias';}
let revMeshes=[];
function revisionsBuild(){const candidates=data.items.filter(i=>/beam/i.test(i.type)&&i.mark&&!i.mark.includes('?')&&i.name==='CONTRAVENTAMENTO');const chosen=[];for(const i of candidates){if(!chosen.some(x=>x.asm===i.asm))chosen.push(i);if(chosen.length===3)break;}
for(let k=0;k<chosen.length;k++){const x=chosen[k];for(const i of data.items.filter(i=>i.asm===x.asm)){const m=meshFor(i);m.userData={...i,change:k};m.material.color.set([0x159768,0xe05b64,0xe3a12f][k]);if(k===0)m.position.y+=.45;if(k===2)m.position.z+=.25;revMeshes.push(m);}}
return chosen;
}
let chosen;
function revisionView(v){overview.forEach(m=>{m.visible=v!=='changes';m.material.color.set(0xc3ced7);m.material.transparent=true;m.material.opacity=.025;m.material.depthWrite=false;});revMeshes.forEach(m=>{m.visible=(v==='before'?m.userData.change!==0:v==='after'?m.userData.change!==1:true);});document.querySelectorAll('[data-rev]').forEach(b=>b.classList.toggle('active',b.dataset.rev===v));draw();}
function revisao(){overview.forEach(m=>group.add(m));revMeshes.forEach(m=>group.add(m));panel.innerHTML=`<h2>O que mudou?</h2><p class="tag">REVISÃO B SIMULADA</p><p>Existe uma única versão deste arquivo no histórico consultado. Este exemplo usa cópias de conjuntos reais para ilustrar a leitura das diferenças.</p><div class="controls"><button data-rev="overlay">Sobrepor</button><button data-rev="changes">Só diferenças</button></div><div class="legend"><span><i class="dot" style="background:#159768"></i>Adicionado</span><span><i class="dot" style="background:#e05b64"></i>Removido</span><span><i class="dot" style="background:#e3a12f"></i>Alterado</span></div><div class="item">+ Cópia ilustrativa de ${esc(chosen[0].mark)}, deslocada 0,45 m</div><div class="item">− Remoção ilustrativa de ${esc(chosen[1].mark)}</div><div class="item">↔ Deslocamento ilustrativo de ${esc(chosen[2].mark)} em 0,25 m</div><p class="note">Nenhuma dessas mudanças foi constatada na obra. Para comparar de verdade, precisamos de dois IFCs do mesmo escopo e validar a correspondência entre elementos.</p><div id="picked" aria-live="polite"></div>`;document.querySelectorAll('[data-rev]').forEach(b=>b.onclick=()=>revisionView(b.dataset.rev));revisionView('overlay');const box=new T.Box3();revMeshes.forEach(m=>box.expandByObject(m));frame(box);status.textContent='Comparação demonstrativa · mudanças simuladas, não revisão da Engenharia';}
function switchMode(m){mode=m;clear();document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));({ligacao,montagem,revisao})[m]();draw();}
document.querySelectorAll('[data-mode]').forEach(b=>{b.disabled=true;b.onclick=()=>switchMode(b.dataset.mode);});
let down;
renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5||mode==='montagem')return;const rect=renderer.domElement.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),cam);const hits=ray.intersectObjects(mode==='ligacao'?detail:revMeshes,false).filter(h=>h.object.visible&&(!h.object.material.clippingPlanes||h.object.material.clippingPlanes.every(p=>p.distanceToPoint(h.point)>=0)));const hit=hits[0];if(!hit)return;const i=hit.object.userData;document.querySelector('#picked').textContent=`${i.name||i.type} · marca ${i.mark||'não informada'} · IFC #${i.id} · ${i.guid}`;});
try{const r=await fetch('/modelo.json');if(!r.ok)throw Error('Arquivo indisponível');data=await r.json();for(const [id,{v,i}] of Object.entries(data.geos)){const p=[],n=[];for(let k=0;k<v.length;k+=6){p.push(v[k],v[k+1],v[k+2]);n.push(v[k+3],v[k+4],v[k+5]);}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p,3));g.setAttribute('normal',new T.Float32BufferAttribute(n,3));g.setIndex(i);parts[id]=g;}overviewBuild();detailBuild();chosen=revisionsBuild();document.querySelectorAll('[data-mode]').forEach(b=>b.disabled=false);switchMode('ligacao');}catch(e){status.textContent=`Falha ao abrir: ${e.message}`;}
