-- Remove ALMOXARIFADO do enum TipoRM. Postgres exige recriar o tipo.
ALTER TYPE "TipoRM" RENAME TO "TipoRM_old";
CREATE TYPE "TipoRM" AS ENUM ('ENGENHARIA', 'INTERNA');
ALTER TABLE "RM" ALTER COLUMN "tipoRM" DROP DEFAULT;
ALTER TABLE "RM" ALTER COLUMN "tipoRM" TYPE "TipoRM" USING ("tipoRM"::text::"TipoRM");
ALTER TABLE "RM" ALTER COLUMN "tipoRM" SET DEFAULT 'ENGENHARIA';
DROP TYPE "TipoRM_old";
