"use client";
import {useEffect,useState} from 'react';
import {Flag,ArrowUp,ArrowDown,Plus,Loader2} from 'lucide-react';
import {useStore} from '@/lib/store';
import {moverFase,fasesReferenciasSchema} from '@/lib/fases-referencias';
const botao='rounded-lg border px-3 py-2 text-sm text-torg-blue disabled:opacity-40';
const campo='w-full min-w-24 rounded border border-gray-200 px-2 py-2 text-sm text-torg-dark';
export default function FasesReferencias({opId,consulta=false}){
 const {showToast}=useStore();
 const [dados,setDados]=useState(null),[erro,setErro]=useState(''),[tentativa,setTentativa]=useState(0),[edit,setEdit]=useState(null),[salvando,setSalvando]=useState(false);
 useEffect(()=>{const c=new AbortController();setDados(null);setErro('');setEdit(null);
 fetch(`/api/comercial/op/${opId}/fases`,{signal:c.signal,cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error);return j;}).then(j=>{if(!c.signal.aborted)setDados(j);}).catch(e=>{if(!c.signal.aborted)setErro(e.message||'Não foi possível carregar as fases.');});return()=>c.abort();},[opId,tentativa]);
 const tabela=edit||dados?.tabela;
 const alterar=(i,chave,valor)=>setEdit(v=>({...v,fases:v.fases.map((f,j)=>j===i?{...f,[chave]:valor}:f)}));
 async function salvar(){const parsed=fasesReferenciasSchema.safeParse(edit);if(!parsed.success){showToast(parsed.error.issues[0].message,'error');return;}
 setSalvando(true);try{const r=await fetch(`/api/comercial/op/${opId}/fases`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({tabela:parsed.data,versao:dados.versao})});const j=await r.json();if(!r.ok)throw Error(j.error);setDados(j);setEdit(null);showToast('Fases e prioridades salvas.','success');}catch(e){showToast(e.message,'error');}finally{setSalvando(false);}}
 return <section className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden" aria-label="Fases e referências do cliente">
 <header className="p-5 flex justify-between flex-wrap gap-3"><div><h3 className="text-lg font-semibold text-torg-dark flex items-center gap-2"><Flag size={18} className="text-torg-blue"/>Fases e referências do cliente</h3><p className="text-sm text-torg-gray mt-1">Correspondência das fases Torg com a numeração do cliente, em ordem de prioridade.</p></div>
 {dados?.podeEditar&&!consulta&&!edit&&<button className={botao} onClick={()=>setEdit(structuredClone(dados.tabela))}>Editar fases</button>}</header>
 {erro?<div className="p-5 text-red-700" role="alert">{erro}<button className={botao+' ml-3'} onClick={()=>setTentativa(v=>v+1)}>Tentar novamente</button></div>:!dados?<p className="p-5 text-torg-gray flex gap-2"><Loader2 className="animate-spin" size={18}/>Carregando fases…</p>:<>
 {edit&&<p className="px-5 pb-3 text-sm text-torg-gray">Edite os nomes das empresas no cabeçalho. Use as setas para definir a sequência. As alterações entram em vigor ao salvar.</p>}
 <fieldset disabled={salvando} className="min-w-0">
 {tabela.fases.length===0&&!edit?<p className="px-5 pb-5 text-sm text-torg-gray">Nenhuma fase cadastrada. A Engenharia pode informar as fases e suas referências antes dos desenhos.</p>:<div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead className="bg-gray-50/60 text-torg-gray"><tr><th className="p-3">Prioridade</th><th className="p-3">Fase Torg</th><th className="p-3 min-w-48">Parte / escopo</th>{tabela.empresas.map((e,k)=><th key={k} className="p-3 min-w-36">{edit?<input aria-label={`Empresa ${k+1}`} className={campo} value={e} onChange={ev=>setEdit(v=>({...v,empresas:v.empresas.map((x,j)=>j===k?ev.target.value:x)}))}/>:e}</th>)}{edit&&<th className="p-3">Ordem</th>}</tr></thead>
 <tbody className="divide-y divide-gray-50">{tabela.fases.map((f,i)=><tr key={i} className={i===0?'bg-blue-50/40':''}><td className="p-3 whitespace-nowrap"><strong>{i+1}ª</strong>{i===0&&<span className="block text-xs text-torg-blue mt-1">Prioridade atual</span>}</td><td className="p-3">{edit?<input aria-label={`Fase ${i+1}`} className={campo} value={f.fase} onChange={e=>alterar(i,'fase',e.target.value)}/>:<strong>{f.fase}</strong>}</td><td className="p-3">{edit?<input aria-label={`Escopo ${i+1}`} className={campo} value={f.descricao} onChange={e=>alterar(i,'descricao',e.target.value)}/>:f.descricao||'—'}</td>{tabela.empresas.map((e,k)=><td key={k} className="p-3">{edit?<input aria-label={`Referência ${e} fase ${i+1}`} className={campo} value={f.referencias[k]||''} onChange={ev=>alterar(i,'referencias',f.referencias.map((x,j)=>j===k?ev.target.value:x))}/>:f.referencias[k]||'—'}</td>)}{edit&&<td className="p-3 whitespace-nowrap"><button className={botao} aria-label={`Subir fase ${f.fase||i+1}`} disabled={i===0} onClick={()=>setEdit(v=>({...v,fases:moverFase(v.fases,i,-1)}))}><ArrowUp size={16}/></button> <button className={botao} aria-label={`Descer fase ${f.fase||i+1}`} disabled={i===tabela.fases.length-1} onClick={()=>setEdit(v=>({...v,fases:moverFase(v.fases,i,1)}))}><ArrowDown size={16}/></button> <button className={botao} aria-label={`Remover fase ${f.fase||i+1}`} onClick={()=>setEdit(v=>({...v,fases:v.fases.filter((_,j)=>j!==i)}))}>Remover</button></td>}</tr>)}</tbody></table></div>}
 {edit&&<div className="p-4 flex flex-wrap gap-3"><button className={botao} onClick={()=>setEdit(v=>({...v,fases:[...v.fases,{fase:'',descricao:'',referencias:v.empresas.map(()=> '')}]}))}><Plus size={14} className="inline"/> Adicionar fase</button><button className={botao} disabled={edit.empresas.length>=8} onClick={()=>setEdit(v=>({...v,empresas:[...v.empresas,''],fases:v.fases.map(f=>({...f,referencias:[...f.referencias,'']}))}))}>Adicionar empresa</button><button className={botao} onClick={()=>{setEdit(null);setTentativa(v=>v+1);}}>Cancelar</button><button className="rounded-lg bg-torg-blue text-white px-4 py-2 text-sm disabled:opacity-40" onClick={salvar}>{salvando?'Salvando…':'Salvar fases'}</button></div>}
 </fieldset></>}
 </section>;
}
