"use client";
import {useEffect,useState} from 'react';
import {ClipboardCheck,Loader2} from 'lucide-react';
import {useStore} from '@/lib/store';
import ConfirmModal from '@/components/admin/ConfirmModal';
import VisualizadorPitPdf from './VisualizadorPitPdf';
import AceitePlano from '@/app/comercial/[id]/AceitePlano';
export default function PitCompacto({opNumero}){
 const {showToast}=useStore();const [pit,setPit]=useState(null),[docs,setDocs]=useState([]),[erro,setErro]=useState(''),[tentativa,setTentativa]=useState(0),[modo,setModo]=useState(''),[padrao,setPadrao]=useState(''),[revisao,setRevisao]=useState('0'),[salvando,setSalvando]=useState(false),[nome,setNome]=useState('PIT do cliente'),[arquivo,setArquivo]=useState(null),[visual,setVisual]=useState(null),[abas,setAbas]=useState(null),[aba,setAba]=useState(0);
 const [excluir,setExcluir]=useState(null),[excluindo,setExcluindo]=useState(false);
 async function confirmarExclusao(){
  if(!excluir||excluindo)return;
  setExcluindo(true);
  try{
   const torg=excluir.tipo==="TORG";
   const r=await fetch(torg?base:base+"/cliente",{method:torg?"PUT":"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify(torg?{padrao:null,revisao:""}:{id:excluir.id})});
   const j=await r.json();if(!r.ok)throw Error(j.error);
   if(torg){setPit(p=>({...p,padrao:null,revisao:"0"}));setPadrao("");setRevisao("0");setModo("");}
   else{setDocs(v=>v.filter(d=>d.id!==excluir.id));if(visual?.id===excluir.id)setVisual(null);}
   showToast(torg?"PIT Torg removido da obra.":"Anexo excluído da consulta.","success");
  }catch(e){showToast(e.message,"error");}finally{setExcluindo(false);setExcluir(null);}
 }

 const base=`/api/qualidade/pit/${encodeURIComponent(opNumero)}`;
 useEffect(()=>{const c=new AbortController();setPit(null);setErro('');setModo('');setVisual(null);Promise.all([fetch(base,{signal:c.signal,cache:'no-store'}),fetch(base+'/cliente',{signal:c.signal,cache:'no-store'})]).then(async rs=>Promise.all(rs.map(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error);return j;}))).then(([p,d])=>{if(c.signal.aborted)return;setPit(p);setDocs(d.documentos);setPadrao(p.padrao||'');setRevisao(p.revisao||'0');}).catch(e=>{if(!c.signal.aborted)setErro(e.message);});return()=>c.abort();},[base,tentativa]);
 async function criar(){if(!padrao)return;setSalvando(true);try{const r=await fetch(base,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({padrao,revisao})});const j=await r.json();if(!r.ok)throw Error(j.error);setPit(p=>({...p,padrao,revisao}));setModo('editar');showToast('PIT Torg salvo. Confira os responsáveis e visualize o PDF.','success');}catch(e){showToast(e.message,'error');}finally{setSalvando(false);}}
 async function anexar(){setSalvando(true);try{const f=new FormData();f.set('nome',nome);f.set('revisao',revisao);f.set('arquivo',arquivo);const r=await fetch(base+'/cliente',{method:'POST',body:f});const j=await r.json();if(!r.ok)throw Error(j.error);setDocs(v=>[j.documento,...v]);setModo('');setArquivo(null);showToast('PIT do cliente anexado.','success');}catch(e){showToast(e.message,'error');}finally{setSalvando(false);}}
 async function visualizar(d){setVisual(d);setAbas(null);setAba(0);if(/\.pdf$/i.test(d.arquivoNome))return;try{const r=await fetch(base+'/cliente?arquivo='+encodeURIComponent(d.id));const j=await r.json();if(!r.ok)throw Error(j.error);setAbas(j.abas);}catch(e){setVisual(null);showToast(e.message,'error');}}
 const b='rounded-lg border border-gray-200 px-3 py-2 text-sm text-torg-blue disabled:opacity-40';const inp='rounded-lg border border-gray-200 p-2 text-sm';
 return <section className="bg-white rounded-xl shadow-sm border border-gray-100 p-4" aria-label="Plano de Inspeção e Testes">
 <header className="flex flex-wrap justify-between items-center gap-3"><h4 className="text-sm font-semibold text-torg-dark flex gap-2 items-center"><ClipboardCheck size={16}/>Plano de Inspeção e Testes (PIT)</h4>{pit?.podeGerenciar&&<div className="flex gap-2"><button className={b} onClick={()=>{setModo('anexar');setRevisao('');}}>Anexar PIT do cliente</button><button className={b} onClick={()=>{setModo(pit.padrao?'editar':'criar');setPadrao(pit.padrao||'');setRevisao(pit.revisao||'0');}}>{pit.padrao?'Editar PIT Torg':'Criar PIT Torg'}</button></div>}</header>
 {erro?<p role="alert" className="mt-3 text-red-700">{erro} <button className={b} onClick={()=>setTentativa(x=>x+1)}>Tentar novamente</button></p>:!pit?<p className="mt-3 text-sm"><Loader2 size={14} className="inline animate-spin"/> Carregando…</p>:<>
 {!pit.padrao&&!docs.length&&!modo&&<p className="mt-3 text-sm text-torg-gray">Nenhum PIT disponibilizado para esta obra.</p>}
 <div className="divide-y divide-gray-100 mt-3">{pit.padrao&&<div className="flex justify-between items-center gap-3 py-2 text-sm"><span><strong>PIT Torg</strong> · {pit.opcoes.find(o=>o.id===pit.padrao)?.nome} · Rev. {pit.revisao}</span><div className="flex shrink-0 gap-2"><a className={b} href={`/api/qualidade/planos/${encodeURIComponent(opNumero)}/pdf?doc=PIT`} target="_blank" rel="noreferrer">Visualizar</a>{pit.podeGerenciar&&<button aria-label="Excluir PIT Torg" className={b+" text-red-700"} onClick={()=>setExcluir({tipo:"TORG"})}>Excluir</button>}</div></div>}{docs.map(d=><div key={d.id} className="flex justify-between items-center gap-3 py-2 text-sm"><span><strong>{d.nome}</strong> · PIT do cliente {d.numeroDocumento&&`· Rev. ${d.numeroDocumento}`}</span><div className="flex gap-2"><button className={b} onClick={()=>visualizar(d)}>Visualizar</button>{pit.podeGerenciar&&<button className={b+" text-red-700"} onClick={()=>setExcluir(d)}>Excluir</button>}</div></div>)}</div>
 {pit.podeGerenciar&&modo&&<fieldset disabled={salvando} className="mt-3 border-t pt-3 min-w-0">
 {modo==='anexar'?<div className="flex flex-wrap gap-2 items-center"><input aria-label="Título do PIT do cliente" className={inp} value={nome} onChange={e=>setNome(e.target.value)}/><input aria-label="Revisão do PIT do cliente" className={inp} placeholder="Revisão" value={revisao} onChange={e=>setRevisao(e.target.value)}/><input aria-label="Arquivo do PIT do cliente" type="file" accept=".pdf,.xlsx,.xls" onChange={e=>setArquivo(e.target.files[0]||null)} className="text-sm max-w-full"/><span className="text-xs text-torg-gray">PDF ou Excel · até 4 MB</span><button className={b} disabled={!arquivo||salvando} onClick={anexar}>{salvando?'Anexando…':'Salvar anexo'}</button></div>:<><div className="flex flex-wrap gap-2 items-center"><label className="text-sm">Modelo <select aria-label="Modelo de PIT" className={inp+' ml-2'} value={padrao} onChange={e=>setPadrao(e.target.value)}><option value="">Selecione o PIT</option>{pit.opcoes.map(o=><option key={o.id} value={o.id}>{o.nome}</option>)}</select></label><input aria-label="Revisão do PIT Torg" className={inp+' w-24'} value={revisao} onChange={e=>setRevisao(e.target.value)}/><button className={b} disabled={!padrao||salvando} onClick={criar}>{salvando?'Salvando…':pit.padrao?'Salvar modelo':'Criar'}</button></div>{padrao&&<p className="mt-2 text-xs text-torg-gray">{pit.opcoes.find(o=>o.id===padrao)?.resumo}</p>}{pit.padrao&&modo==='editar'&&<AceitePlano opNumero={opNumero} doc="PIT" nome="o PIT"/>}</>}
 <button className={b+' mt-3'} onClick={()=>setModo('')}>Fechar edição</button></fieldset>}
 </>}
 {visual&&<div className="mt-4 border-t pt-3"><div className="flex justify-between gap-2 mb-3"><strong className="text-sm">{visual.nome}</strong><button className={b} onClick={()=>setVisual(null)}>Fechar consulta</button></div>{/\.pdf$/i.test(visual.arquivoNome)?<VisualizadorPitPdf key={visual.id} src={`${base}/cliente?arquivo=${encodeURIComponent(visual.id)}`}/>:!abas?<p>Carregando planilha…</p>:<><select aria-label="Aba da planilha" className={inp} value={aba} onChange={e=>setAba(Number(e.target.value))}>{abas.map((a,i)=><option key={i} value={i}>{a.nome}</option>)}</select><p className="text-xs text-torg-gray my-2">Prévia dos valores salvos · até 2.000 linhas e 100 colunas por aba. O original é preservado.</p><div className="overflow-auto max-h-[60vh]"><table className="text-xs border-collapse"><tbody>{abas[aba]?.linhas.map((l,i)=><tr key={i}>{l.map((v,j)=><td key={j} className="border p-2 whitespace-pre-wrap min-w-24">{String(v)}</td>)}</tr>)}</tbody></table></div></>}</div>}
 <ConfirmModal open={!!excluir} onClose={()=>setExcluir(null)} onConfirm={confirmarExclusao} titulo={excluir?.tipo==="TORG"?"Excluir PIT Torg?":"Excluir PIT do cliente?"} mensagem={excluir?.tipo==="TORG"?"O modelo de PIT deixará de estar selecionado nesta obra. Os anexos do cliente serão mantidos e você poderá criar outro PIT depois.":`O documento “${excluir?.nome||''}” deixará de aparecer para consulta nesta OP. O registro e o arquivo serão preservados no histórico.`} labelConfirmar={excluir?.tipo==="TORG"?"Excluir PIT":"Excluir anexo"} variant="destrutivo" loading={excluindo}/>
 </section>;
}
