'use client';
import {useEffect,useState} from 'react';
import {upload} from '@vercel/blob/client';
import {FileText,Plus,CheckCircle2,Link2,X,Upload,History,Search} from 'lucide-react';
const API='/api/comercial/produtos/tintas';
const vazio={fabricante:'',produto:'',categoria:'TINTA',tipo:'PRIMER',boletimUrl:'',boletimNome:'',boletimRevisao:'',boletimData:'',solidosVol:'',secaMin:'',secaMax:'',componenteA:'',componenteB:'',proporcaoMistura:'',diluente:'',diluicaoMin:'',diluicaoMax:'',observacoes:'',ativo:true};
const campo='mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-200';
const acao='rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-medium hover:bg-slate-50 disabled:opacity-50';
async function json(url,init){const r=await fetch(url,init),j=await r.json();if(!r.ok)throw new Error(j.error||'Não foi possível concluir.');return j;}
export default function BoletinsClient(){
 const [dados,setDados]=useState({tintas:[],fornecedores:[]}),[carregando,setCarregando]=useState(true),[erro,setErro]=useState(''),[nota,setNota]=useState('');
 const [aba,setAba]=useState('produtos'),[busca,setBusca]=useState(''),[editor,setEditor]=useState(null),[arquivo,setArquivo]=useState(null),[conferido,setConferido]=useState(false),[ocupado,setOcupado]=useState(false),[historico,setHistorico]=useState(null),[vinculos,setVinculos]=useState({});
 async function carregar(){const j=await json(API);setDados(j);setVinculos(Object.fromEntries(j.fornecedores.map(f=>[f.id,f.fabricanteTinta||''])));}
 useEffect(()=>{carregar().catch(e=>setErro(e.message)).finally(()=>setCarregando(false));},[]);
 const fabricantes=[...new Set([...dados.tintas.map(t=>t.fabricante),...dados.fornecedores.map(f=>f.fabricanteTinta)].filter(Boolean))].sort();
 const lista=dados.tintas.filter(t=>`${t.produto} ${t.fabricante}`.toLowerCase().includes(busca.toLowerCase()));
 function editar(t){setEditor(t?{...vazio,...t}:{...vazio});setArquivo(null);setConferido(false);setErro('');setNota('');}
 function set(k,v){setEditor(p=>({...p,[k]:v}));setConferido(false);}
 async function anexar(file){
  if(!file)return;
  if(!/\.pdf$/i.test(file.name)){setErro('Selecione um boletim PDF.');return;}
  setOcupado(true);setErro('');setArquivo(file);
  try{const blob=await upload(`boletins-tinta/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`,file,{access:'public',handleUploadUrl:'/api/comercial/produtos/tintas/upload-token'});setEditor(p=>({...p,boletimUrl:blob.url,boletimNome:file.name}));setConferido(false);setNota('PDF anexado. Confira os dados técnicos abaixo antes de salvar.');}catch(e){setErro(e.message);}finally{setOcupado(false);}
 }
 async function extrair(){
  if(!arquivo)return;
  if(arquivo.size>3*1024*1024){setNota('Para leitura automática, envie até 3 MB. O PDF já está anexado; você pode preencher os dados manualmente.');return;}
  setOcupado(true);setErro('');
  try{
   const b64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(arquivo);});
   const j=await json('/api/qualidade/tintas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({somenteExtrair:true,arquivo:b64,arquivoNome:arquivo.name,contentType:'application/pdf'})});
   const t=j.tintas?.find(x=>x.categoria==='TINTA')||j.tintas?.[0];
   if(!t)throw new Error('Nenhum produto reconhecido. Preencha os dados manualmente.');
   setEditor(p=>({...p,...Object.fromEntries(Object.entries(t).filter(([k])=>k in vazio && !['boletimUrl','boletimNome','boletimRevisao','boletimData'].includes(k)))}));
   setConferido(false);setNota(`Leitura concluída${j.tintas.length>1?' — o documento contém vários produtos; confira o produto selecionado':''}. A leitura é um rascunho: confira com o PDF.`);
  }catch(e){setNota(`Leitura automática indisponível. O PDF foi preservado: preencha os dados manualmente. ${e.message}`);}finally{setOcupado(false);}
 }
 async function salvar(e){
  e.preventDefault();setOcupado(true);setErro('');
  const payload={...editor,conferido};
  for(const k of ['solidosVol','secaMin','secaMax','diluicaoMin','diluicaoMax'])payload[k]=editor[k]===''||editor[k]==null?null:Number(String(editor[k]).replace(',','.'));
  try{await json(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});await carregar();setEditor(null);setNota('Boletim conferido salvo. A revisão anterior permanece no histórico.');}catch(e2){setErro(e2.message);}finally{setOcupado(false);}
 }
 async function vincular(f){setOcupado(true);setErro('');try{await json(API,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({fornecedorId:f.id,fabricanteTinta:vinculos[f.id]||null})});await carregar();setNota('Vínculo de fabricante salvo.');}catch(e){setErro(e.message);}finally{setOcupado(false);}}
 const input=(k,label,extra={})=><label className="text-xs font-semibold text-slate-600">{label}<input className={campo} value={editor[k]??''} onChange={e=>set(k,e.target.value)} {...extra}/></label>;
 return <div className="mx-auto max-w-7xl space-y-6">
  <header className="rounded-2xl bg-[#0d1f3c] p-7 text-white"><p className="text-xs uppercase tracking-[.2em] text-blue-200">Engenharia Comercial · Catálogo técnico</p><div className="mt-3 flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-semibold">Produtos e boletins de tintas</h1><p className="mt-2 max-w-2xl text-sm text-slate-300">Cadastre as fichas por fabricante e confira os dados que sustentam as sugestões nas consultas da LQC.</p></div><button className="flex items-center gap-2 rounded-lg bg-white px-4 py-3 text-sm font-semibold text-[#0d1f3c]" onClick={()=>editar()}><Plus size={17}/> Cadastrar boletim</button></div></header>
  {erro&&<p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{erro}</p>}
  {nota&&!editor&&<p role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{nota}</p>}
  <nav className="flex gap-2 border-b border-slate-200 pb-3"><button onClick={()=>setAba('produtos')} className={`${acao} ${aba==='produtos'?'!bg-[#0d1f3c] !text-white':''}`}><FileText className="mr-2 inline" size={16}/> Boletins ({dados.tintas.length})</button><button onClick={()=>setAba('vinculos')} className={`${acao} ${aba==='vinculos'?'!bg-[#0d1f3c] !text-white':''}`}><Link2 className="mr-2 inline" size={16}/> Fornecedores e fabricantes</button></nav>
  {carregando?<p className="text-sm text-slate-500">Carregando cadastro…</p>:aba==='produtos'?<>
   <label className="flex max-w-lg items-center gap-2 rounded-xl border border-slate-200 bg-white px-3"><Search size={17} className="text-slate-400"/><input aria-label="Buscar produto ou fabricante" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar produto ou fabricante" className="w-full bg-transparent py-3 text-sm outline-none"/></label>
   {!lista.length&&<div className="rounded-xl border border-dashed border-slate-300 p-12 text-center text-slate-500">Nenhum boletim encontrado. Cadastre o PDF e confira os dados técnicos.</div>}
   <div className="grid gap-4 lg:grid-cols-2">{lista.map(t=><article key={t.id} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-blue-700">{t.fabricante}</p><h2 className="mt-1 text-lg font-semibold text-slate-900">{t.produto}</h2></div><span className={`rounded-full px-2 py-1 text-xs ${!t.ativo?'bg-slate-100 text-slate-500':t.conferidoEm?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-800'}`}>{!t.ativo?'Inativo':t.conferidoEm?'Conferido':'A conferir'}</span></div><p className="mt-3 text-sm text-slate-600">{t.tipo||t.categoria} · {t.solidosVol??'—'}% sólidos · {t.secaMin??'—'}–{t.secaMax??'—'} µm</p><p className="mt-1 text-xs text-slate-500">Revisão {t.boletimRevisao||'não informada'} · {t.boletimData||'sem data'}</p><div className="mt-4 flex flex-wrap gap-2"><button className={acao} onClick={()=>editar(t)}>Conferir / nova revisão</button>{t.boletimUrl&&/^https:\/\//.test(t.boletimUrl)&&<a className={acao} href={t.boletimUrl} target="_blank" rel="noreferrer"><FileText className="mr-1 inline" size={14}/>PDF</a>}{t.historicoBoletins?.length>0&&<button className={acao} onClick={()=>setHistorico(t)}><History className="mr-1 inline" size={14}/>Histórico ({t.historicoBoletins.length})</button>}</div></article>)}</div>
  </>:<section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold">Qual fabricante cada fornecedor representa?</h2><p className="mb-5 mt-1 text-sm text-slate-500">O vínculo é explícito. Sem fabricante vinculado, a consulta solicita a especificação do produto e não sugere boletins.</p><datalist id="fabricantes-tinta">{fabricantes.map(f=><option key={f} value={f}/>)}</datalist>{!dados.fornecedores.length&&<p className="text-sm text-slate-500">Cadastre fornecedores de tintas na Vendor List do Compras.</p>}<div className="divide-y divide-slate-100">{dados.fornecedores.map(f=><div key={f.id} className="grid items-center gap-3 py-4 md:grid-cols-[1fr_1fr_auto]"><div><b className="text-sm text-slate-800">{f.nome}</b><p className="text-xs text-slate-500">{f.email||'Sem e-mail na Vendor List'}</p></div><input aria-label={`Fabricante de ${f.nome}`} className={campo} list="fabricantes-tinta" placeholder="Fabricante (vínculo manual)" value={vinculos[f.id]||''} onChange={e=>setVinculos(p=>({...p,[f.id]:e.target.value}))}/><button disabled={ocupado||(vinculos[f.id]||'')===(f.fabricanteTinta||'')} className={acao} onClick={()=>vincular(f)}>Salvar vínculo</button></div>)}</div></section>}
  {editor&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 p-4"><form onSubmit={salvar} role="dialog" aria-modal="true" aria-label="Cadastro de boletim" className="max-h-[94vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-wider text-blue-700">Cadastro técnico</p><h2 className="text-xl font-semibold">{editor.id?'Conferir / revisar boletim':'Cadastrar boletim'}</h2></div><button type="button" aria-label="Fechar cadastro" onClick={()=>setEditor(null)} disabled={ocupado}><X/></button></div>
   {erro&&<p role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{erro}</p>}{nota&&<p role="status" className="mt-3 rounded-lg bg-blue-50 p-3 text-sm text-blue-800">{nota}</p>}
   <div className="my-5 rounded-xl border border-dashed border-blue-200 bg-blue-50/40 p-4"><label className="flex cursor-pointer items-center gap-2 text-sm font-semibold text-blue-800"><Upload size={18}/> {ocupado?'Processando…':'Anexar boletim PDF'}<input type="file" accept="application/pdf,.pdf" className="hidden" disabled={ocupado} onChange={e=>anexar(e.target.files?.[0])}/></label>{editor.boletimUrl&&<a href={editor.boletimUrl} target="_blank" rel="noreferrer" className="mt-2 block text-sm text-blue-700 underline">{editor.boletimNome}</a>}<p className="mt-2 text-xs text-slate-500">Preencha manualmente ou use a leitura automática como rascunho. Somente a conferência salva libera sugestões.</p>{arquivo&&<button type="button" className={`${acao} mt-3`} onClick={extrair} disabled={ocupado}>Ler dados do PDF com IA</button>}</div>
   <div className="grid gap-4 sm:grid-cols-2">{input('fabricante','Fabricante',{required:true})}{input('produto','Produto',{required:true})}<label className="text-xs font-semibold text-slate-600">Categoria<select className={campo} value={editor.categoria} onChange={e=>set('categoria',e.target.value)}><option>TINTA</option><option>DILUENTE</option><option>ENDURECEDOR</option></select></label><label className="text-xs font-semibold text-slate-600">Tipo de demão<select className={campo} value={editor.tipo||''} onChange={e=>set('tipo',e.target.value)}><option value="">Não se aplica</option><option value="PRIMER">Primer</option><option value="INTERMEDIARIA">Intermediária</option><option value="ACABAMENTO">Acabamento</option><option value="UNICA">Única</option></select></label>{input('boletimRevisao','Revisão do boletim',{required:true})}{input('boletimData','Data do boletim',{type:'date',required:true})}{input('solidosVol','Sólidos por volume (%)',{inputMode:'decimal',required:editor.categoria==='TINTA'})}{input('secaMin','Película seca mínima (µm)',{inputMode:'decimal',required:editor.categoria==='TINTA'})}{input('secaMax','Película seca máxima (µm)',{inputMode:'decimal',required:editor.categoria==='TINTA'})}{input('componenteA','Componente A')}{input('componenteB','Componente B')}{input('proporcaoMistura','Proporção de mistura')}{input('diluente','Diluente do fabricante')}{input('diluicaoMin','Diluição mínima (%)',{inputMode:'decimal'})}{input('diluicaoMax','Diluição máxima (%)',{inputMode:'decimal'})}</div>
   <label className="mt-4 block text-xs font-semibold text-slate-600">Observações técnicas<textarea className={campo} rows={3} value={editor.observacoes||''} onChange={e=>set('observacoes',e.target.value)}/></label>
   <label className="mt-4 flex gap-2 text-sm text-slate-600"><input type="checkbox" checked={editor.ativo} onChange={e=>set('ativo',e.target.checked)}/>Produto ativo no catálogo</label>
   <label className="my-5 flex gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900"><input type="checkbox" checked={conferido} onChange={e=>setConferido(e.target.checked)} required/>Conferi fabricante, produto, revisão, PDF e dados técnicos com o boletim. A correspondência será apenas uma sugestão para confirmação do fabricante.</label><footer className="flex justify-end gap-3"><button type="button" className={acao} onClick={()=>setEditor(null)} disabled={ocupado}>Cancelar</button><button type="submit" disabled={ocupado||!conferido||!editor.boletimUrl} className="rounded-lg bg-[#006eab] px-5 py-3 text-sm font-semibold text-white disabled:opacity-40"><CheckCircle2 className="mr-2 inline" size={16}/>Salvar revisão conferida</button></footer>
  </form></div>}
  {historico&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 p-4"><section role="dialog" aria-modal="true" aria-label="Histórico de revisões" className="max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-semibold">Histórico · {historico.produto}</h2><button aria-label="Fechar histórico" onClick={()=>setHistorico(null)}><X/></button></div><p className="mt-2 text-sm text-slate-500">Revisões anteriores preservadas. As consultas enviadas mantêm a ficha usada na ocasião.</p>{[...historico.historicoBoletins].reverse().map((h,i)=><article className="mt-4 rounded-lg border border-slate-200 p-4" key={i}><b>{h.fabricante} · {h.produto} · revisão {h.boletimRevisao||'não informada'}</b><p className="mt-1 text-sm text-slate-500">{h.boletimData||'Sem data'} · {h.solidosVol??'—'}% sólidos · {h.secaMin??'—'}–{h.secaMax??'—'} µm</p><p className="text-xs text-slate-500">{h.conferidoPorNome?`Conferido por ${h.conferidoPorNome}`:'Sem conferência registrada'}</p>{h.boletimUrl&&/^https:\/\//.test(h.boletimUrl)&&<a className="mt-2 block text-sm text-blue-700 underline" href={h.boletimUrl} target="_blank" rel="noreferrer">{h.boletimNome||'Abrir PDF anterior'}</a>}</article>)}</section></div>}
 </div>;
}
