-- CreateEnum
CREATE TYPE "TipoRM" AS ENUM ('ENGENHARIA', 'ALMOXARIFADO', 'INTERNA');

-- DropForeignKey
ALTER TABLE "RM" DROP CONSTRAINT "RM_opId_fkey";

-- AlterTable
ALTER TABLE "RM" ADD COLUMN     "categoriasOP" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "tipoRM" "TipoRM" NOT NULL DEFAULT 'ENGENHARIA',
ALTER COLUMN "opId" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "RM" ADD CONSTRAINT "RM_opId_fkey" FOREIGN KEY ("opId") REFERENCES "OP"("id") ON DELETE SET NULL ON UPDATE CASCADE;
